ui/console/src/main/webapp/index.html
ui/console/src/main/webapp/scripts/controllers/dashboard-controller.ts
ui/console/src/main/webapp/scripts/controllers/sidebar-controller.ts
ui/console/src/main/webapp/scripts/directives/date-time-range-selection-directive.js
ui/console/src/main/webapp/scripts/services/dashboard-state-service.ts
ui/console/src/main/webapp/scripts/services/metric-data-service.ts
ui/console/src/main/webapp/views/main-dashboard.tpl.html

This is a more robust way to coordinated state changes between controllers versus the existing event coordination.

Refactor console ui to Dashboard state service

---

pom.xml
rest-servlet/pom.xml
rest-servlet/src/main/java/org/rhq/metrics/restServlet/MetricsServiceProducer.java
rest-servlet/src/main/java/org/rhq/metrics/restServlet/config/Configurable.java
rest-servlet/src/main/java/org/rhq/metrics/restServlet/config/ConfigurableProducer.java
rest-servlet/src/main/java/org/rhq/metrics/restServlet/config/ConfigurationKey.java
rest-servlet/src/main/java/org/rhq/metrics/restServlet/config/ConfigurationProperty.java
rest-servlet/src/main/resources/META-INF/metrics.conf
rest-servlet/src/test/java/org/rhq/metrics/restServlet/config/ConfigurableProducerTest.java

This pull request contains the "external configuration" aspects of PR #119 (configuration and management).

External config

---

clients/ptranslator/pom.xml
clients/ptranslator/src/assembly/dist/assembly.xml
clients/ptranslator/src/assembly/dist/assets/LICENSE
clients/ptranslator/src/assembly/dist/assets/README
clients/ptranslator/src/assembly/dist/assets/log4j.xml
clients/ptranslator/src/assembly/dist/assets/ptrans.conf
clients/ptranslator/src/main/resources/log4j.xml

For now, there's only a simple env/start script facility, shamelessly copied from the Wildfly equivalents.
We can add instructions on how to use as a service later.

Intial support of a ptrans distribution

---

rest-servlet/src/main/java/org/rhq/metrics/restServlet/config/ConfigurableProducer.java

Effective configuration can be loaded on startup: instead of looping on default and config file properties,
we can loop on configuration keys and check if value is present in default, config file, or sys prop.
This eliminates the need for maintaining a set of already read system properties.
Also, simplified config file and property loading code.

REST: eagerly load effective configuration

---

clients/ptranslator/log4j-dev.xml
clients/ptranslator/ptrans.conf
clients/ptranslator/src/assembly/dist/assets/ptrans.conf
clients/ptranslator/src/main/java/org/rhq/metrics/clients/ptrans/Configuration.java
clients/ptranslator/src/main/java/org/rhq/metrics/clients/ptrans/ConfigurationKey.java
clients/ptranslator/src/main/java/org/rhq/metrics/clients/ptrans/DemuxHandler.java
clients/ptranslator/src/main/java/org/rhq/metrics/clients/ptrans/Main.java
clients/ptranslator/src/main/java/org/rhq/metrics/clients/ptrans/OptionsFactory.java
clients/ptranslator/src/main/java/org/rhq/metrics/clients/ptrans/PTrans.java
clients/ptranslator/src/main/java/org/rhq/metrics/clients/ptrans/backend/RestForwardingHandler.java

Added a Configuration class (wrapping all properties)
Extracted from Main the code for loading configuration
Extracted from Main the code for starting/stopping a ptrans instance given an instance of Configuration
This separation will make it easy to later implement a "reload" signal.

ptrans update

---

clients/common/src/main/java/org/rhq/metrics/client/common/SingleMetric.java
clients/common/src/test/java/org/rhq/metrics/client/common/SingleMetricTest.java
clients/ptranslator/ptrans.conf
clients/ptranslator/src/assembly/dist/assets/ptrans.conf

* Metrics JSON format has changed
* Post data URI change

clients-common and ptrans update following REST changes

---

clients/ptranslator/pom.xml
clients/ptranslator/src/test/java/org/rhq/metrics/clients/ptrans/MainITest.java
clients/ptranslator/src/test/resources/ptrans.conf
pom.xml

ptrans had no basic tests for command line behavior

ptrans basic tests

---

ui/console/src/main/webapp/bower.json
ui/explorer/src/main/webapp/bower.json

Upgrade moment version

---

README.adoc

Note: I didn't change `ccm create -v 2.1.2 rhq` as I am not sure if anything still depend on it

Updated links and RHQ->Hawkular

---

clients/ptranslator/pom.xml
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/PTrans.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/collectd/CollectdEventHandler.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/collectd/event/CollectdEventsDecoder.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/collectd/event/DataType.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/collectd/event/Event.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/collectd/event/TimeResolution.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/collectd/event/TimeSpan.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/collectd/event/ValueListEvent.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/collectd/packet/CollectdPacket.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/collectd/packet/CollectdPacketDecoder.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/collectd/packet/NumericPart.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/collectd/packet/Part.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/collectd/packet/PartType.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/collectd/packet/StringPart.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/collectd/packet/ValuePart.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/collectd/packet/Values.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/collectd/util/Assert.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/collectd/DumpToLog.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/collectd/DumpToLogEventHandler.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/collectd/event/CollectdEventsDecoderTest.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/collectd/event/TimeResolutionTest.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/collectd/packet/CollectdPacketDecoderTest.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/collectd/packet/PacketDecodingTest.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/collectd/util/AssertTest.java

Copy Netty collectd code from RHQ org repo

Copy Netty collectd code from RHQ org repo

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/DataInsertedCallback.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/Error.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/TenantsHandler.java
rest-tests/src/test/groovy/org/hawkular/metrics/rest/CassandraBackendITest.groovy

(cherry picked from commit b68d812a3fa8039baf6173f4b3f70148b2dad7b8)

[HWKMETRICS-30] Error descriptions are returned with Error class

---

clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/collectd/CollectdEventHandler.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/collectd/event/CollectdEventsDecoder.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/collectd/event/ValueListEvent.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/collectd/packet/CollectdPacket.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/collectd/packet/CollectdPacketDecoder.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/collectd/packet/Values.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/collectd/event/CollectdEventsDecoderTest.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/collectd/packet/CollectdPacketDecoderTest.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/collectd/packet/PacketDecodingTest.java

Fix issues found by Sonar in ptrans

Fix issues found by Sonar in ptrans

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/callback/TaggedDataCallback.java

Move all the tagged data data callbacks to their own class and at the same time fix the difference between return codes of these methods (all of them return 204 now on empty resultset).

[HWKMETRICS-29] Matching handling for all tagged data calls

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/ReaderExceptionMapper.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/TenantsHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/callback/EntityCreatedCallback.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/callback/MetricCreatedCallback.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/callback/TenantCreatedCallback.java
rest-tests/src/test/groovy/org/hawkular/metrics/rest/CassandraBackendITest.groovy
rest-tests/src/test/groovy/org/hawkular/metrics/rest/RESTTest.groovy
rest-tests/src/test/groovy/org/hawkular/metrics/rest/TenantITest.groovy

HWKMETRICS-29 Create method return codes should be consistent

HWKMETRICS-29 Create method return codes should be consistent

---

api/metrics-api-jaxrs/pom.xml
pom.xml

- swagger rest base api url modifed to hawkular-metrics
- renamed 'rhq-metrics' to 'hawkular-metrics' under hawkular-metrics/pom.xml

[HAWKULAR-76] swagger rest base api url modifed to hawkular-metrics

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricHandler.java
core/metrics-core-api/pom.xml
core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/AvailabilityBucketDataPoint.java
core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/BucketedOutput.java
core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/Buckets.java
core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/MetricsService.java
core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/NumericBucketDataPoint.java
core/metrics-core-impl/pom.xml
core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/cassandra/AvailabilityBucketedOutputMapper.java
core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/cassandra/BucketedOutputMapper.java
core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/cassandra/MetricsServiceCassandra.java
core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/cassandra/NumericBucketedOutputMapper.java
core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/cassandra/AvailabilityBucketDataPointMatcher.java
core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/cassandra/AvailabilityBucketedOutputMapperTest.java
core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/cassandra/DataAccessITest.java
core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/cassandra/MetricsITest.java
core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/cassandra/MetricsServiceCassandraITest.java
rest-tests/pom.xml
rest-tests/src/test/groovy/org/hawkular/metrics/rest/AvailabilityMetricStatisticsITest.groovy
rest-tests/src/test/groovy/org/hawkular/metrics/rest/NumericMetricStatisticsITest.groovy

HWKMETRICS-35 Availability REST API Calculations Required for MVP2 given a date range?

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/TenantsHandler.java
core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/cassandra/MetricsServiceCassandra.java

Fixes HWKMETRICS-44 Tenant list endpoint does not report internal server error correctly
Tenant list was making a synchronous call: `dataAccess.findAllTenantIds().getUninterruptibly()`
So if C* was stopped, the exception wouldn't bubble up through the ListenableFuture chain, but rather through the Wildfly HTTP handler stack.

HWKMETRICS-44 Tenant list endpoint does not report internal server error correctly

---

rest-tests/src/test/groovy/org/hawkular/metrics/rest/RESTTest.groovy

REST test: output response body when an error is not expected

REST test: output response body when an error is not expected

---

.travis.yml
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/collectd/event/TimeResolution.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/ExecutableITestBase.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/PidFileITest.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/PrintOutputOnFailureWatcher.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/fullstack/CollectdITest.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/util/ProcessUtil.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/util/TenantUtil.java
clients/ptranslator/src/test/resources/collectd.conf

This is a PR to run an end to end regression test on Travis (collectd, ptrans, hawkular-metrics)
Not ready for merge, initial work only.

HWKMETRICS-37 collectd/ptrans/metrics full stack integration test

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/param/ConvertersProvider.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/param/Duration.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/param/DurationConverter.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/param/Tags.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/param/TagsConverter.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/swagger/filter/JaxRsFilter.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/util/ApiUtils.java
api/metrics-api-jaxrs/src/main/resources/rest-doc/duration.json
api/metrics-api-jaxrs/src/main/resources/rest-doc/tags.json
api/metrics-api-jaxrs/src/test/java/org/hawkular/metrics/api/jaxrs/param/InvalidDurationConverterTest.java
api/metrics-api-jaxrs/src/test/java/org/hawkular/metrics/api/jaxrs/param/InvalidTagsConverterTest.java
api/metrics-api-jaxrs/src/test/java/org/hawkular/metrics/api/jaxrs/param/TagsConverterTest.java
rest-tests/src/test/groovy/org/hawkular/metrics/rest/CassandraBackendITest.groovy
rest-tests/src/test/groovy/org/hawkular/metrics/rest/RESTTest.groovy
rest-tests/src/test/groovy/org/hawkular/metrics/rest/TagsITest.groovy

Please don't merge. I'm waiting for #188 to be merged. Then I'll rebase/adjust this one.

HWKMETRICS-26 REST-API uses return codes incorrectly

---

core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/cassandra/MetricsServiceCassandra.java

Replaces duplicate code with a single reusable instance for both metricData types.

Replace tagging async transformers with a single function class

---

clients/ptranslator/ptrans.conf
clients/ptranslator/src/assembly/dist/assets/ptrans.conf
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/Configuration.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/ConfigurationKey.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/backend/RestForwardingHandler.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/ConfigurationITest.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/OpenedPortsITest.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/PTransTest.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/backend/RestForwardingHandlerITest.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/fullstack/CollectdITest.java
clients/ptranslator/src/test/resources/ptrans.conf

HWKMETRICS-84 Update ptrans to use tenant as a request header

---

.travis.swagger.sh

Check on the consumer side is made also here https://github.com/hawkular/hawkular.github.io/blob/pages/.travis.swagger.sh#L23
this PR is based on #206

Don't push empty docs

---

containers/cassandra-seed-provider/src/main/java/org/hawkular/openshift/cassandra/OpenshiftSeedProvider.java

Add checks on the cassandra-nodes service before initilizing the seed list.

HWKMETRICS-88

---

containers/cassandra-docker/pom.xml
containers/hawkular-metrics-docker/pom.xml

Add a profile to assembly all the docker files together. 
For local docker image building purposes.

HWKMETRICS-89

---

containers/cassandra-docker/src/main/docker/Dockerfile
containers/cassandra-docker/src/main/docker/cassandra-docker-pre-stop.sh
containers/cassandra-docker/src/main/docker/cassandra-docker.sh
containers/kubernetes/src/main/fabric8/kubernetes.json

HWKMETRICS-87: the Cassandra containers are now able to be scaled down using a replication controller. This will properly decommission them from the cluster
HWKMETRICS-98: Store the Cassandra data to a volume instead of storing it within the container itself.

HWKMETRICS-87 & HWKMETRICS-98

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/InfluxSeriesHandler.java
rest-tests/src/test/groovy/org/hawkular/metrics/rest/InfluxITest.groovy
rest-tests/src/test/java/org/hawkular/metrics/test/InfluxDatabaseITest.java

Three itests fail on my box. The timestamps in the Influx response do not match expectations. Strangely enough, they are correctly sent to the server, but when the data is read back, the value is different.
Does that ring a bell @jsanda ?

HWKMETRICS-82 Refactor InfluxSeriesHandler

---

api/metrics-api-jaxrs/src/main/antlr4/org/hawkular/metrics/api/jaxrs/influx/query/parse/InfluxQuery.g4
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/InfluxObject.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/InfluxSeriesHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/query/parse/definition/SelectQueryDefinitionsParser.java
api/metrics-api-jaxrs/src/test/resources/influx/query/supported-select-queries.iql
api/metrics-api-jaxrs/src/test/resources/influx/query/syntactically-correct-queries.iql
clients/ptranslator/log4j-dev.xml
rest-tests/src/test/groovy/org/hawkular/metrics/rest/InfluxITest.groovy
rest-tests/src/test/java/org/hawkular/metrics/test/InfluxDBTest.java
rest-tests/src/test/java/org/hawkular/metrics/test/InfluxDatabaseITest.java

This one must be merged after PR #220

Port changes from PR #220 to rx-migration branch

---

.travis.yml

Add in the hooks to automatically build the docker images when the build completes successfully.

HWKMETRICS-92

---

api/metrics-api-jaxrs/pom.xml
embedded-cassandra/embedded-cassandra-ear/pom.xml
embedded-cassandra/embedded-cassandra-service/pom.xml
pom.xml

Use definitions from new parent POM version

Use definitions from new parent POM version

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/filter/MetricsServiceStateFilter.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/filter/TenantFilter.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/StatusHandler.java
rest-tests/src/test/groovy/org/hawkular/metrics/rest/StatusITest.groovy

Create a status endpoint to display the state of things such as the MetricsService.
WIP: do not merge yet.

HWKMETRICS-104

---

containers/hawkular-metrics-docker/src/main/docker/Dockerfile
containers/hawkular-metrics-docker/src/main/docker/hawkular-metrics-liveness.sh
containers/hawkular-metrics-docker/src/main/docker/hawkular-metrics-poststart.sh
containers/kubernetes/src/main/fabric8/kubernetes.json

Add liveness probes and postStartup hooks to the hawkular metrics containers.
Update to use kubernetes v1beta03 api.

HWKMETRICS-103

---

load-tests/README.adoc
load-tests/pom.xml
load-tests/src/test/resources/gatling.conf
load-tests/src/test/scala/org/hawkular/metrics/loadtest/MetricsSimulation.scala
pom.xml

Create a Gatling load testing scenario

HWKMETRICS-115 Create a Gatling load testing scenario

---

clients/ptranslator/ptrans.conf
clients/ptranslator/src/assembly/dist/assets/ptrans.conf
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/Configuration.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/ConfigurationKey.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/backend/RestForwardingHandler.java
clients/ptranslator/src/test/resources/ptrans.conf

HWKMETRICS-116 Allow ptrans to work behind an HTTP proxy

HWKMETRICS-116 Allow ptrans to work behind an HTTP proxy

---

embedded-cassandra/embedded-cassandra-service/pom.xml
embedded-cassandra/embedded-cassandra-service/src/main/java/org/hawkular/metrics/embedded/ConfigEditor.java
embedded-cassandra/embedded-cassandra-service/src/main/resources/cassandra.yaml

Please review.
The JIRA mentions problems with long shutdown times after this change. We should investigate that before merging this.

[HWKMETRICS-120] Start Thrift Server in embedded Cassandra service.

---

clients/ptranslator/README.adoc
clients/ptranslator/pom.xml
clients/ptranslator/src/assembly/dist/assets/README

Minor updates and fixes to the ptrans docs

ptrans docs update

---

README.adoc
api/metrics-api-jaxrs/README.adoc

An update to reflect the current state of the project and highlight goals.

Project README update

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java
core/metrics-core-impl/pom.xml
core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/DataAccess.java
core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/DataAccessImpl.java
core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/MetricsServiceImpl.java
core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/DelegatingDataAccess.java
core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/MetricsServiceITest.java
pom.xml

This commit includes instrumentation for both gauges and availability.

[HWKMETRICS-136] add instrumentation for reading/writing raw data

---

containers/cassandra-docker/src/main/docker/Dockerfile
containers/cassandra-docker/src/main/docker/cassandra-docker-ready.sh
containers/cassandra-docker/src/main/docker/cassandra-docker.sh
containers/container-tests/pom.xml
containers/container-tests/src/test/java/org/hawkular/containers/BaseContainerTests.java
containers/container-tests/src/test/java/org/hawkular/containers/TestCassandraScaling.java
containers/container-tests/src/test/java/org/hawkular/containers/TestContainers.java
containers/container-tests/src/test/java/org/hawkular/containers/TestMetrics.java
containers/hawkular-metrics-docker/src/main/docker/hawkular-metrics-poststart.sh
containers/hawkular-metrics-docker/src/main/resources/assemblies/assemble-docker.xml
containers/kubernetes/src/main/fabric8/kubernetes.json
containers/pom.xml

Add in container tests (enabled via profile) and fixes required for the tests.

HWKMETRICS-90

---

clients/ptranslator/src/assembly/dist/assembly.xml

Minor changes to assembly file

HWKMETRICS-141 ptrans distribution file layout is broken

---

api/metrics-api-jaxrs/pom.xml
clients/common/pom.xml
clients/pom.xml
clients/ptranslator/pom.xml
containers/cassandra-docker/pom.xml
containers/cassandra-seed-provider/pom.xml
containers/container-tests/pom.xml
containers/hawkular-metrics-docker/pom.xml
containers/kubernetes/pom.xml
containers/kubernetes/src/main/fabric8/kubernetes.json
containers/pom.xml
core/metrics-core-api/pom.xml
core/metrics-core-impl/pom.xml
load-tests/pom.xml
pom.xml
rest-tests/pom.xml
rx-java-driver/pom.xml
schema-manager/pom.xml
task-queue/pom.xml

Use C* driver and Guava version from parent + mvn tidy:pom

POM changes

---

core/metrics-core-api/pom.xml
core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/Aggregate.java
core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/MetricsService.java
core/metrics-core-impl/pom.xml
core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/MetricsServiceImpl.java
core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/MetricsServiceITest.java
pom.xml

- override findGaugeData with a new signature that can apply one or
more functions to the fetched data (uses a single fetch)
- provide some built in aggregate functions to be used with the new
findGaugeData signature out-of-box.

HWKMETRICS-144 Support server-side gauge data aggregate fetch

---

clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/backend/RestForwardingHandler.java

The buffer with the metrics REST response was not released.
Replaced inbound handler with SimpleChannelInboundHandler (autorelease).

HWKMETRICS-143 ptrans: ByteBuf leak in REST forwarding handler

---

clients/ptranslator/pom.xml
clients/ptranslator/ptrans.conf
clients/ptranslator/src/assembly/dist/assets/ptrans.conf
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/Configuration.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/ConfigurationKey.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/DemuxHandler.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/PTrans.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/Service.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/graphite/GraphiteChannelInitializer.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/graphite/GraphiteEventDecoder.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/fullstack/CollectdITest.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/fullstack/FullStackITest.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/fullstack/GraphiteITest.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/fullstack/MetricData.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/fullstack/MetricName.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/fullstack/Point.java
clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/fullstack/ServerDataHelper.java
clients/ptranslator/src/test/resources/jmxtrans.json
clients/ptranslator/src/test/resources/ptrans.conf

Do not merge yet. I've found issues in the current graphite listener and I'm also adding a new itest (with embedded jmxtrans).

PTrans Graphite text protocol strenghtening

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/param/ConvertersProvider.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/param/MetricTypeConverter.java
api/metrics-api-jaxrs/src/test/java/org/hawkular/metrics/api/jaxrs/param/MetricTypeConverterTest.java
core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/MetricType.java
rest-tests/src/test/groovy/org/hawkular/metrics/rest/CassandraBackendITest.groovy

List metrics endpoint fails with 500 Internal Server Error when "type" param is missing

---

containers/Readme.md
containers/cassandra-docker/pom.xml
containers/cassandra-docker/src/main/docker/Dockerfile
containers/hawkular-metrics-docker/pom.xml
containers/hawkular-metrics-docker/src/main/docker/Dockerfile

Update to work with OpenShift v3 1.0.0, document how to run the container tests.

HWKMETRICS-159

---

containers/cassandra-docker/pom.xml
containers/container-tests/pom.xml
containers/container-tests/src/test/java/org/hawkular/containers/BaseContainerTests.java
containers/container-tests/src/test/java/org/hawkular/containers/TestContainers.java
containers/hawkular-metrics-docker/pom.xml
containers/kubernetes/pom.xml
containers/kubernetes/src/main/fabric8/kubernetes.json
containers/pom.xml

Add docker-push profile to push images out to a docker registry.

HWKMETRICS-165

---

.travis.install.cassandra.sh
.travis.yml

Do not merge yet. Initial commit and testing.

Move to  Travis container based infra

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/ApiError.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/observer/ResultSetObserver.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/InfluxSeriesHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/util/ApiUtils.java
containers/cassandra-seed-provider/src/main/java/org/hawkular/openshift/cassandra/OpenshiftSeedProvider.java
core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/GaugeBucketDataPoint.java
core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/MetricAlreadyExistsException.java
core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/MetricType.java
core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/MetricsThreadFactory.java
core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/TenantAlreadyExistsException.java
core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/TenantDoesNotExistException.java
core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/BucketedOutputMapper.java
core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/GenerateRate.java
core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/MetricsServiceImpl.java
core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/VoidSubscriber.java
schema-manager/src/main/java/org/hawkular/metrics/schema/TokenReplacingReader.java
task-queue/src/main/java/org/hawkular/metrics/tasks/api/TaskExecutionException.java

These are fixes coming from the SonarQube analysis of the metrics-database.

Fix lots of small static analysis issues

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/exception/mappers/ReaderExceptionMapper.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/filter/EmptyPayloadFilter.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/TenantsHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/interceptor/EmptyPayloadException.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/interceptor/EmptyPayloadInterceptor.java
rest-tests/src/test/groovy/org/hawkular/metrics/rest/AvailabilityITest.groovy
rest-tests/src/test/groovy/org/hawkular/metrics/rest/CountersITest.groovy
rest-tests/src/test/groovy/org/hawkular/metrics/rest/GaugesITest.groovy
rest-tests/src/test/groovy/org/hawkular/metrics/rest/InfluxITest.groovy
rest-tests/src/test/groovy/org/hawkular/metrics/rest/TenantITest.groovy

Updates handlers and added tests. Also made the behavior consistent across endpoints.

HWKMETRICS-176 REST: make sure all POST requests with empty body return 400 Empty payload

---

containers/cassandra-docker/src/main/docker/cassandra.yaml

Remove the EC ciphers since OpenJDK doesn't currently support them properly.

HWKMETRICS-209

---

core/metrics-core-impl/pom.xml
core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/DataAccess.java
core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/DataAccessImpl.java
core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/MetricsServiceImpl.java
core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/transformers/BatchStatementTransformer.java
core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/DataAccessITest.java
core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/DelegatingDataAccess.java
core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/MetricsServiceITest.java
core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/transformers/BatchStatementTransformerTest.java
rest-tests/src/test/groovy/org/hawkular/metrics/rest/AvailabilityITest.groovy
rest-tests/src/test/groovy/org/hawkular/metrics/rest/CountersITest.groovy
rest-tests/src/test/groovy/org/hawkular/metrics/rest/GaugesITest.groovy
rest-tests/src/test/groovy/org/hawkular/metrics/rest/RESTTest.groovy

C* batch size is limited to 0xFFFF. This fix lets the user submit a payload of arbitrary size.

HWKMETRICS-215 IllegalStateException: Batch statement cannot contain more than 65535 statements

---

core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/MetricsInitializationITest.java

Force test ordering by using a single method instead of using the 'dependsOnMethod' option which interweaves tests.

HWKMETRICS-229

---

core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/DataAccessImpl.java
core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/MetricsServiceImpl.java
core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/MetricsServiceITest.java

Fetches the tenant_ids from metrics_idx table as well as tenant table and then returns the tenants.

[HWKMETRICS-190] Fetch tenantIds from the metrics_idx table also

---

api/diff-pre-commit-hook.sh
api/diff.txt
api/metrics-api-jaxrs-1.1/src/main/java/org/hawkular/metrics/api/jaxrs/request/MetricDefinition.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/request/MetricDefinition.java
pom.xml

Metrics dev should add this hook to their local repo. Whenever we introduce changes which impact the diff, the file will show up on GH. So it will help both the developer and the reviewer to make sure the impls do not diverge.

Pre-commit hook sample for JAX-RS diffs

---

api/metrics-api-common/src/main/java/org/hawkular/metrics/api/jaxrs/util/Headers.java
api/metrics-api-common/src/main/java/org/hawkular/metrics/api/jaxrs/util/OriginValidation.java
api/metrics-api-jaxrs-1.1/src/main/java/org/hawkular/metrics/api/jaxrs/config/ConfigurationKey.java
api/metrics-api-jaxrs-1.1/src/main/java/org/hawkular/metrics/api/jaxrs/filter/CorsFilter.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/config/ConfigurationKey.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/filter/CorsRequestFilter.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/filter/CorsResponseFilter.java
rest-tests/pom.xml
rest-tests/src/test/groovy/org/hawkular/metrics/rest/CORSITest.groovy
tests/rest-integration-tests-jaxrs-1.1/pom.xml

Also add tests to verify the CORS origin policy is enforced properly.

[HWKMETRICS-236] Make the CORS origin configurable.

---

api/diff.txt
api/metrics-api-common/pom.xml
api/metrics-api-jaxrs-1.1/pom.xml
api/metrics-api-jaxrs/pom.xml
containers/cassandra-docker/pom.xml
containers/cassandra-seed-provider/pom.xml
containers/container-tests/pom.xml
containers/hawkular-metrics-docker-eap/pom.xml
containers/hawkular-metrics-docker/pom.xml
containers/kubernetes-eap/pom.xml
containers/kubernetes/pom.xml
integration-tests/load-tests/pom.xml
integration-tests/pom.xml
integration-tests/rest-tests-jaxrs-1.1/pom.xml
integration-tests/rest-tests-jaxrs/pom.xml
rx-java-driver/pom.xml
schema-manager/pom.xml
task-queue/pom.xml

Removed redundant dependency declaration and fixed some parent/child issues

Minor POM fixes

---

core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/DataAccess.java
core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/DataAccessImpl.java
core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/Functions.java
core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/MetricsServiceImpl.java
core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/DataAccessITest.java
core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/DelegatingDataAccess.java
schema-manager/src/main/resources/schema.cql

The storage and queries are to be done via the metrics_idx table.

[HWKMETRICS-254] Remove m_tags field and usage from the data table.

---

clients/common/pom.xml
clients/pom.xml
clients/ptranslator/pom.xml

HWKMETRICS-131 rename artifacts so they are less generic
Renamed clients and clients-common to hawkular-metrics-clients and hawkular-metrics-clients-common
Also fixed a parent reference issue

HWKMETRICS-131 rename artifacts so they are less generic

---

README.adoc

Update doc to reflect C* 2.2 dependency (as discussed with Thomas H and the team)

Update doc to reflect C* 2.2 dependency

---

CONTRIBUTING.adoc

Created a CONTRIBUTING.adoc file and added the logging convention stuff in there.

Metrics specific logging conventions doc

---

core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/MetricsServiceImpl.java
core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/MetricsServiceITest.java
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CountersITest.groovy

HWKMETRICS-265 Counter "rate" returning same data as "data" endpoint
In the previous implementation, we used to:
- sort out counter data points in one minute buckets
- compute rate based on low and high value
The implementation had the following issues:
- if there's just one point per minute in the original counter, you get a rate metric similar to the original counter metric
- if there's less that one point per minute you get a rate metric with many `NaN` values
The new implementation has a basic approach:
- buffer counter data observable into "previous/next" pairs
- compute rate for each pair, where timestamp is the average of timestamps in the pair
Let's take an example. Consider the following counter data points:
```
{"timestamp":0,"value":0}
{"timestamp":30000,"value":50} …
```

HWKMETRICS-265 Counter "rate" returning same data as "data" endpoint

---

api/diff.txt
api/metrics-api-jaxrs-1.1/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java
core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/MetricsService.java
core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/NumericBucketPoint.java
core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/MetricsServiceImpl.java
core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/NumericDataPointCollector.java
core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/MetricsServiceITest.java
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CountersITest.groovy
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/GaugeMetricStatisticsITest.groovy
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/RESTTest.groovy

**Do not merge yet.**
This pull request holds the changes for HWKMETRICS-280 Counter Rate data does not support buckets.
I will soon add the changes needed to compute counter data buckets.

Counter and rate buckets

---

api/metrics-api-common/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java
containers/pom.xml

Add support for client auth with a Cassandra cluster
Update to use Cassandra 2.2.1

HWKMETRICS-294

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java
core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/MetricsService.java
core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/MetricsServiceImpl.java
core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/MetricsServiceITest.java
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CountersITest.groovy

We now filter out those windows in which the second value is less than the
first.

[HWKMETRICS-218] [HWKMETRICS-284] handle counter reset events

---

core/metrics-core-impl/pom.xml

Fix test-ng build error
Force junit provider in surefire plugin, testng provider in failsafe plugin

Fix test-ng build error

---

api/metrics-api-jaxrs-1.1/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java
api/metrics-api-jaxrs-1.1/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java
api/metrics-api-jaxrs-1.1/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java
api/metrics-api-jaxrs-1.1/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsService.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/MetricsServiceITest.java
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/TagsITest.groovy

Change signature of findMetricsWithFilters to accept new Func1 filters such as id filter and make the signature consistent with findMetric definition order.

[HWKMETRICS-234] findMetricsWithFilters to accept new filters

---

hawkular-component/pom.xml
hawkular-component/src/main/java/org/hawkular/metrics/security/PersonaFilter.java
hawkular-component/src/main/webapp/WEB-INF/jboss-web.xml
hawkular-component/src/main/webapp/WEB-INF/web.xml
integration-tests/hawkular-server-tests/pom.xml
integration-tests/hawkular-server-tests/server-provisioning.xml
integration-tests/hawkular-server-tests/src/main/resources/standalone.xsl
integration-tests/hawkular-server-tests/src/test/groovy/org/hawkular/metrics/AuthenticationITest.groovy
integration-tests/pom.xml
pom.xml

Reapplied HWKMETRICS-69

---

README.adoc

Doc should now refer to Wildfly 10

Doc should now refer to Wildfly 10

---

containers/hawkular-metrics-openshift-integration/src/main/java/org/hawkular/openshift/auth/OpenShiftTokenAuthentication.java

Update required to function properly with latest builds from origin master due to api changes.

HWKMETRICS-350

---

core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java

BucketPointCollector instances can be emitted in any order (coming from a flatMap of a groupObservable).

HWKMETRICS-353 Stacked metrics not ordered in any way

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/util/JacksonConfig.java
api/metrics-api-jaxrs/src/main/webapp/WEB-INF/web.xml
clients/ptranslator/pom.xml
clients/ptranslator/ptrans.conf
clients/ptranslator/src/assembly/dist/assets/ptrans.conf
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/Configuration.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/ConfigurationKey.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/Main.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/ServerType.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/backend/Constants.java
clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/backend/MetricsSender.java
clients/ptranslator/src/test/resources/ptrans.conf
hawkular-component/src/main/webapp/WEB-INF/web.xml
pom.xml

Added new config properties:
- server.type: metrics/hawkular
- auth.id
- auth.secret
- persona.id
tenant config property is now only used when server.type == metrics

HWKMETRICS-342 ptrans should work with a Metrics server protected by Accounts

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java
pom.xml

There were some changes to the SSLOptions API in the driver. See
https://datastax-oss.atlassian.net/browse/JAVA-841 for details.

[HWKMETRICS-359] upgrade C* driver to version 3.0.0

---

core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccess.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccessImpl.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/DataAccessITest.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/DelegatingDataAccess.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/MetricsServiceITest.java
core/rx-java-driver/pom.xml
core/rx-java-driver/src/main/java/org/hawkular/rx/cassandra/driver/ResultSetToRowsTransformer.java
core/rx-java-driver/src/main/java/org/hawkular/rx/cassandra/driver/RxSession.java
core/rx-java-driver/src/main/java/org/hawkular/rx/cassandra/driver/RxSessionImpl.java
core/rx-java-driver/src/test/java/org/hawkular/rx/cassandra/driver/MockResultSet.java
core/rx-java-driver/src/test/java/org/hawkular/rx/cassandra/driver/MockRow.java
core/rx-java-driver/src/test/java/org/hawkular/rx/cassandra/driver/ResultSetToRowsTransformerTest.java

Implemented a ResultSetToRowsTransformer, with backpressure support.

HWKMETRICS-357 Rx computation threads may block while iterating over C* rows

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/param/PercentilesConverter.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsService.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/TaggedDataPointCollector.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/MetricsServiceITest.java
core/metrics-model/src/main/java/org/hawkular/metrics/model/TaggedBucketPoint.java
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CountersITest.groovy
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/GaugeMetricStatisticsITest.groovy
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/RESTTest.groovy

This PR add support for tag based bucketing of gauges. I will do the work for counters in a separate, follow up PR.

HWKMETRICS-373

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/StringHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/util/MetricTypeTextConverter.java
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/GaugesITest.groovy
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/RESTTest.groovy
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/TagsITest.groovy

Add endpoints for creating, updating, and querying String metric definitions and tags. Also extend existing tag tests to String metric type.

[HWKMETRICS-402]

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/QueryRequest.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricsServiceHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/StringHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/observer/NamedDataPointObserver.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/util/JacksonConfig.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/util/ObjectMapperProducer.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsService.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java
core/metrics-model/src/main/java/org/hawkular/metrics/model/NamedDataPoint.java
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/AvailabilityITest.groovy
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CountersITest.groovy
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/GaugesITest.groovy
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/RESTTest.groovy
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/StringITest.groovy

This PR is *not* ready to merge. I still have refactoring to do to reduce duplicate code, add javadocs, and clean up error handling. I am ready though to start getting some feedback. I have taken a different approach with these new endpoints in that I am streaming the response rather than realizing it entirely in memory before sending to the client.

HWKMETRICS-393

---

containers/hawkular-metrics-openshift-integration/src/main/java/org/hawkular/openshift/auth/TokenAuthenticator.java

Simple switch to allow us to enable or disable users from writing metrics into the system.
This is to allow the system to be locked down so that something only like Heapster will have access to be able to write metrics.

Disable users from being able to write metrics by default.

---

job-scheduler/src/test/java/org/hawkular/metrics/scheduler/impl/JobExecutionTest.java

I had this change made already at some point and I guess it got reverted back
during a merge.

relax verification check

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/StringHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/template/IMetricsHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/param/DurationConverter.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/Order.java
core/metrics-model/src/main/java/org/hawkular/metrics/model/param/Duration.java
core/metrics-model/src/main/java/org/hawkular/metrics/model/param/TimeRange.java
core/metrics-model/src/test/java/org/hawkular/metrics/model/param/TimeRangeTest.java

See https://issues.jboss.org/browse/HWKMETRICS-358

Add in support for relative timestamps.

---

core/schema/src/main/resources/org/hawkular/schema/updates/schema-0.18.0.groovy

Opening the PR for review, but let's not merge just yet. I want to spend a little time doing some more performance testing to make sure we are good to go.

[HWKMETRICS-454] use deflat compressor for data table

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/QueryRequest.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/StatsQueryRequest.java
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/MetricsITest.groovy

See https://issues.jboss.org/browse/HWKMETRICS-457

Add relative timestamps to the query endpoints.

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/QueryRequest.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/StatsQueryRequest.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/StringHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/template/IMetricsHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/param/DurationConverter.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/Order.java
core/metrics-model/src/main/java/org/hawkular/metrics/model/param/Duration.java
core/metrics-model/src/main/java/org/hawkular/metrics/model/param/TimeRange.java
core/metrics-model/src/test/java/org/hawkular/metrics/model/param/TimeRangeTest.java
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/MetricsITest.groovy

(cherry picked from commit 9d4a19752474a55148cb0b89453a66472c8d42e4)

Add support for relative timestamps.

---

core/schema/src/main/resources/org/hawkular/schema/updates/schema-0.18.0.groovy

@mwringe can you test this since the error I got was different than what you reported?

[HWKMETRICS-458] explicitly set keyspace due to cassalog bug

---

bus/src/main/java/org/hawkular/metrics/component/publish/InsertedDataSubscriber.java
hawkular-component/src/main/java/org/hawkular/metrics/component/insert/NewDataListener.java

Note: this is pure trial and fail/success attempt...
On my machine, Hawkular Services starts when those 2 @Eager are removed, but I don't know what else needs to be tested...

HWKMETRICS-450: Removing @Eager to make Hawkular Services start

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/TagsITest.groovy

If no tags are defined, but id filter is, go for exact matching with a list separated by `|`
@lponce

[HWKMETRICS-461] Allow fetching multiple metric definitions with id list

---

bus/src/main/java/org/hawkular/metrics/component/publish/PublishCommandTable.java

A bug in an integration test on hawkular-services (https://issues.jboss.org/browse/HAWKULAR-1121) has masked a problem not detected until now.
Storing an object as a key for published cache requires to share same classloader between libraries used by metrics and alert.
So a workaround is to use a primitive type as proposed on this fix.
Counter part on alerting and fixed itest on hawkular-services are on the way.
/cc @stefannegrea @jshaughn

HAWKULAR-1121 Store string as a key on PublishCache

---

bus/src/main/java/org/hawkular/metrics/component/publish/PublishCommandTable.java

Enable additional debug logging

HAWKULAR-1121 Store string as a key on PublishCache for 0.19.0 branch

---

core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java

Currently setting TTL to anything else than default will cause the TTL to be seconds instead of days we advertise in the API docs..

Fix getTTL to calculate the seconds for insert processes

---

job-scheduler/src/test/java/org/hawkular/metrics/scheduler/impl/JobExecutionTest.java

I want to disable this test in master so it doesn't hold up other PRs, and I will continue to work on a fix in a brach.

travis is failing with this test for other PRs due to HWKMETRICS-477

---

dist/standalone-ear/pom.xml
dist/standalone-war/pom.xml
integration-tests/rest-tests-jaxrs-dist/pom.xml
pom.xml

@stefannegrea Please review and merge for inclusion in 0.20

Ensure proper alerting hooks in place in standalone deployment

---

pom.xml

In preparation of alerting release move to most recent commit:
- Up alerting SRC dep
- Up commons dep to lates version to match alerting

Up alerting SRC dep

---

alerting/alerting-jar/src/main/java/org/hawkular/metrics/alerting/InsertedDataSubscriber.java
api/metrics-api-util/src/main/java/org/hawkular/metrics/api/jaxrs/config/ConfigurationKey.java

- Now defaults to 100 but can be changed via configuration

HWKMETRICS-516 Make batch size configurable in InsertedDataSubscriber

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/filter/AdminFilter.java
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/TenantITest.groovy

It currently returns 400 for all the error situations, this makes it 400 for missing code and 403 for incorrect code

[HWKMETRICS-528] Fix error code of missing admin filter

---

alerting/alerting-jar/src/main/java/org/hawkular/metrics/alerting/InsertedDataSubscriber.java

HWKMETRICS-531 Fix issue with buffer size initialization.

HWKMETRICS-531

---

alerting/alerting-jar/src/main/java/org/hawkular/metrics/alerting/InsertedDataSubscriber.java

[HWKMETRICS-531] Fix issue with buffer size initialization.

---

clients/ptranslator/pom.xml
pom.xml

to the jaxrs war, which is no longer a formal dist.
(cherry picked from commit c6229ef9b5cbbd3cf2af22fd61a0e915f68fbaf3)

Migrate ptrans ITest to run against standalone ear as opposed

---

alerting/alerter-war/src/main/java/org/hawkular/metrics/alerter/ExpressionManager.java
alerting/alerting-jar/src/test/java/org/hawkular/alerts/api/services/AlertsServiceMock.java
dist/component/component-war/src/main/webapp/WEB-INF/web.xml
pom.xml

- adapt to internal api change
- updates for new locks cache

HWKMETRICS-540 Update to Alerting 1.3.2

---

dist/component/component-war/src/main/webapp/WEB-INF/web.xml

Fix Hservices deployment issue.

HWKMETRICS-541 Add new cache resources to the component war web.xml overlay.

---

dist/component/component-ear/pom.xml
dist/component/component-ear/src/main/application/META-INF/jboss-deployment-structure.xml
dist/containers/hawkular-metrics-openshift-dist/pom.xml
dist/containers/hawkular-metrics-openshift-dist/src/main/application/META-INF/jboss-deployment-structure.xml
dist/standalone/standalone-ear/pom.xml
dist/standalone/standalone-ear/src/main/application/META-INF/jboss-deployment-structure.xml
integration-tests/rest-tests-jaxrs-dist/pom.xml
integration-tests/rest-tests-jaxrs-dist/src/main/application/META-INF/jboss-deployment-structure.xml
integration-tests/rest-tests-jaxrs/pom.xml
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/alerting/AlertingITest.groovy

- Initial plugins to be packaged are email and webhook.
- Add email action test (optional manual verification)

HWKMETRICS-552 Add Alerting Action Plugins to Distributions

---

clients/ptranslator/pom.xml
dist/standalone/wildfly-standalone/src/main/xsl/subsystem-templates/hawkular-alerting-infinispan.xsl
integration-tests/rest-tests-jaxrs/pom.xml
pom.xml

@stefannegrea Please review/merge.

Bump alerting src dep and update compatibility

---

integration-tests/load-tests/README.adoc
integration-tests/load-tests/pom.xml
integration-tests/load-tests/src/test/resources/gatling.conf
integration-tests/load-tests/src/test/scala/org/hawkular/metrics/loadtest/MetricsSimulation.scala

I have also updated the version of Gatling since we were behind a bit.

[HWKMETRICS-559] add support for duration option

---

job-scheduler/src/main/java/org/hawkular/metrics/scheduler/impl/JobsService.java
job-scheduler/src/main/java/org/hawkular/metrics/scheduler/impl/SchedulerImpl.java

When jobs fall behind and are rescheduled for immediate execution, we first
renew the job lock. The job should only be executed again if the lock is
successfully renewed. We were always executing the job. This is fixed.
When there are jobs to execute across multiple time slices, we were executing
things out of order. This is fixed simply by replacing flatMap with concatMap
in a few places.
When retrying a job execution, we were updating finished_jobs_idx with the
wrong timestamp. We were using the trigger time instead of the time in which
the job is scheduled. In this scenario, the scheduled time != the trigger time.

[HWKMETRICS-564] fix several bugs

---

core/metrics-core-service/src/main/java/org/hawkular/metrics/core/dropwizard/DropWizardReporter.java

(cherry picked from commit af66de6b339bfb3705584a2afbdd1f8bdd02b854)

[HWKMETRICS-574] Change dropWizard logging to debug

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/observer/NamedDataPointObserver.java
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/GaugesITest.groovy

They were missing on POST query endpoints (*/raw/query)

HWKMETRICS-588 Add datapoint tags to some reponses

---

job-scheduler/src/main/java/org/hawkular/metrics/scheduler/impl/Lock.java
job-scheduler/src/main/java/org/hawkular/metrics/scheduler/impl/LockManager.java
job-scheduler/src/main/java/org/hawkular/metrics/scheduler/impl/SchedulerImpl.java

[PR 742](https://github.com/hawkular/hawkular-metrics/pull/742) needs to be merged before this.

[HWKMETRICS-570] add support for automatic job lock renewal

---

pom.xml

@stefannegrea Please review. Contains fix for schema update blocker.  @jsanda Please sanity check upgrade fix after merge.  Thanks!

Bump Alerting to 1.5.1.Final

---

pom.xml

Bump to alerting 1.5.1.Final release

---

containers/hawkular-openshift-security-filter/src/main/java/org/hawkular/openshift/auth/TokenAuthenticator.java

Do not retry token authorization if connection was successful, but the response was not what we wanted.
@mwringe

[HWKMETRICS-591] Incorrect token authorization takes longer than correct..

---

core/schema/src/main/java/org/hawkular/metrics/schema/SchemaService.java
core/schema/src/main/resources/org/hawkular/schema/bootstrap.groovy
pom.xml

We cannot merge this until [hawkular-alerts PR 292](https://github.com/hawkular/hawkular-alerts/pull/292) is merged and a new version of hawkular-alerts is released.

[HWKMETRICS-594] make bootstrap script handle shutdowns and restarts

---

.travis.install.cassandra.sh
core/schema/src/main/java/org/hawkular/metrics/schema/SchemaService.java

Update to TWCS if it is available on Cassandra's classpath.

HWKMETRICS-608

---

alerting/alerter-war/src/main/java/org/hawkular/metrics/alerter/ConditionExpression.java
alerting/alerter-war/src/main/java/org/hawkular/metrics/alerter/ConditionManager.java
alerting/alerter-war/src/test/java/org/hawkular/metrics/alerter/ConditionExpressionTest.java
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/alerting/ExternalAlerterITest.groovy

@lucasponce  This feature may be OK as is but we should keep it open until things are clear for hwkalerts-240.

HWKMETRICS-630 Alert quietCount option

---

core/schema/src/main/java/org/hawkular/metrics/schema/SchemaService.java

Note that this is for the release/0.21.0 branch.

[HWKMETRICS-606] change compaction strategy of metrics_idx to STCS

---

pom.xml

(cherry picked from commit f4570a0d128e6e1f9a83706d518830d917e7d76c)

HWKMETRICS-644 H Alerts 1.6.2.Final

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/MetricsITest.groovy

(cherry picked from commit 8bac297c91c5bc2e7efb0432baf9748260e4380b)

[HWKMETRICS-621] Make /m a short alternative path to /metrics.

---

integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/alerting/GroupTriggerAlerterITest.groovy

HWKMETRICS-649 GroupTriggerAlerterITest fails in slow environments

---

pom.xml

Matches version with vert.x platform

[HWKMETRICS-650] Upgrade rxjava 1.2.6 -> 1.2.7

---

core/metrics-core-service/pom.xml

See HWKMETRICS-662 for details

Disable problematic tests from build until we get them fixed

---

alerting/alerter-war/src/main/java/org/hawkular/metrics/alerter/ConditionManager.java
alerting/alerter-war/src/main/java/org/hawkular/metrics/alerter/groups/GroupTriggerManager.java
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/alerting/GroupTriggerAlerterITest.groovy
pom.xml

@stefannegrea I discovered a few issues in the alerter while writing a tutorial lesson for alerting.  Once merged to master these fixes should be applied to the 0.26 line for OS.

HWKMETRICS-673 Metrics Alerter fixes

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java
api/metrics-api-util/src/main/java/org/hawkular/metrics/api/jaxrs/config/ConfigurationKey.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/dropwizard/HawkularMetricRegistry.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/dropwizard/HawkularObjectNameFactory.java

Note that PR 836 needs to be merged before this.

Back port HWKMETRICS-689 to release/0.27.0 branch

---

core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/transformers/DataPointDecompressTransformer.java

Reverts hawkular/hawkular-metrics#845

Revert "Logging for testing"

---

core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/SumNumericBucketPointCollector.java
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/GaugesITest.groovy

[HWKMETRICS-698] Manage percentiles in SumNumericBucketPointCollector

---

api/metrics-api-jaxrs/pom.xml
core/schema/src/main/resources/org/hawkular/schema/updates/schema-0.21.0.groovy
core/schema/src/main/resources/org/hawkular/schema/updates/schema-0.26.0.groovy
pom.xml

I also had to change the git url to use https in the scm plugin.
The git checkout failed for me when using git://

[HWKMETRICS-722] add verification updates for schema updates

---

core/schema/src/main/java/org/hawkular/metrics/schema/SchemaService.java
core/schema/src/main/resources/org/hawkular/schema/updates/schema-0.27.0.groovy

The change is done with the 0.27.x tag since we want this change on the 0.27.0
branch as well.

[HWKMETRICS-724] update data table to use TWCS

---

ansible-build/README.md
ansible-build/ansible.cfg
ansible-build/hawkular.yml
ansible-build/hosts
ansible-build/roles/create_image/defaults/main.yml
ansible-build/roles/create_image/tasks/main.yml
ansible-build/roles/create_image/templates/Dockerfile
ansible-build/roles/create_image/templates/config.properties
ansible-build/roles/create_image/templates/docker-compose.yml
ansible-build/roles/create_image/templates/hawkular-metrics-wrapper.sh
ansible-build/roles/create_image/templates/logging.properties
ansible-build/roles/create_image/templates/standalone.conf
ansible-build/roles/create_image/templates/standalone.xml
pom.xml

Hey Guys, 
It is a working progress of a docker container. 
It compiles the latest version of hawkular metrics. 
I think this might improve the way we deliver the latest code for new developers and might also flat the curve learning on delivering hawkular metrics + Cassandra on the same box.
Another benefits which I see:
- Most Actual Hawkular Metrics Code (Master Branch)
- Increase the testability by converting to a docker container
When next branch comes, it will need modifications for get vertex working there.
Best Regards,
Guilherme Baufaker Rêgo

[HWKMETRICS-688] Docker Container

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java

Thus the driver will take care of retries

[HWKMETRICS-732] setDefaultIdempotence for driver to true

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/filter/CacheControlFilter.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/BaseHandler.java
api/metrics-api-util/src/main/java/org/hawkular/metrics/api/jaxrs/config/ConfigurationKey.java

Default to no-cache, but also add a config key to possibly override it.

HWKMETRICS-736 (openshift) add explicit Cache-Control header

---

pom.xml

netty 4.0.33.Final -> 4.0.37.Final (sync with cassandra driver transitive dep)
rxjava 1.2.7.Final -> 1.2.9.Final (sync with hawkular-services)

Dependency sync with hawk services

---

alerting/alerter-war/src/main/java/org/hawkular/metrics/alerter/ConditionManager.java
alerting/alerter-war/src/main/java/org/hawkular/metrics/alerter/groups/GroupTriggerManager.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricsServiceHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/StringHandler.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/jobs/CompressData.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccess.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccessImpl.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsService.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/tags/ExpressionTagQueryParser.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/tags/SimpleTagQueryParser.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/transformers/MetricIdentifierFromFullDataRowTransformer.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/jobs/DeleteTenantITest.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/DataAccessITest.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/DelegatingDataAccess.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/CounterITest.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/ExpressionTagQueryITest.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/GaugeITest.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/MixedMetricsITest.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/TagsITest.java

I'm reviewing this..  do not merge yet.

Remove MetricId -> Metric enrichment from places where it is not needed

---

core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccess.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccessImpl.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/tags/SimpleTagQueryParser.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/DelegatingDataAccess.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/tags/SimpleTagQueryParserTest.java

This is a backport of HWKMETRICS-751

[HWKMETRICS-753] Improve simple tag query performance by enabling the A-cost query pos

---

clients/dropwizard/hawkular-dropwizard-reporter/pom.xml
clients/ptranslator/pom.xml
core/schema-installer/README.adoc
core/schema-installer/pom.xml
integration-tests/rest-tests-jaxrs/pom.xml

* [HWKMETRICS-764] fix schema-installer build

[HWKMETRICS-764] back port to release/0.30.0

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/log/HttpErrorLoggerExtension.java
api/metrics-api-jaxrs/src/main/resources/META-INF/services/io.undertow.servlet.ServletExtension

[HWKMETRICS-761] Log REST endpoint details when there is an error

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/servlet/OpenshiftServlet.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/servlet/rx/ObservableServlet.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/jobs/TempDataCompressor.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccess.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccessImpl.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/DataAccessITest.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/DelegatingDataAccess.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/TestDataAccessFactory.java

WIP, will check for bugs later..

[HWKMETRICS-771] compressBlock will check for all possible blocks to compress

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricsServiceHandler.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/StringHandler.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/jobs/CompressData.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccess.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccessImpl.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsService.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/TagQueryParser.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/transformers/MetricIdentifierFromFullDataRowTransformer.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/transformers/TagsIndexRowTransformerFilter.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/jobs/DeleteTenantITest.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/DataAccessITest.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/DelegatingDataAccess.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/CounterITest.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/GaugeITest.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/MixedMetricsITest.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/TagsITest.java

[HWKMETRICS-760] Remove MetricId -> Metric enrichment from places where it is not needed

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java
api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/util/SchemaVersionChecker.java
core/configuration-service/src/test/java/org/hawkular/metrics/sysconfig/ConfigurationServiceTest.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/BaseITest.java
core/schema-installer/src/main/java/org/hawkular/metrics/schema/Installer.java
core/schema/src/main/java/org/hawkular/metrics/schema/SchemaService.java
core/schema/src/main/resources/org/hawkular/schema/bootstrap.groovy
job-scheduler/src/test/java/org/hawkular/metrics/scheduler/impl/JobSchedulerTest.java
pom.xml

[HWKMETRICS-783] release/0.30.0 branch

---

api/metrics-api-jaxrs/src/main/resources/META-INF/services/javax.ws.rs.ext.Providers
pom.xml

* upgrade to WF 11
* update parent pom version
* try to force update to fix travis
* revert change

WF 11 upgrade - release/0.30.0 branch

---

core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java
core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/tags/SimpleTagQueryParser.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/TagsITest.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/tags/SimpleTagQueryParserTest.java
integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/TenantITest.groovy

This is a continuation of [PR 960](https://github.com/hawkular/hawkular-metrics/pull/960).

[HWKMETRICS-787] optimize for pod_id queries

---

core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/tags/SimpleTagQueryParser.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/TagsITest.java

Also update test to cover scenario that triggered the NPE.

[HWKMETRICS-789] fix filtering on groupAOREntries to prevent NPE

---

core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/tags/SimpleTagQueryParser.java
core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/TagsITest.java

Also update test to cover scenario that triggered the NPE.

[HWKMETRICS-789] release/0.30.0 branch

---

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java
api/metrics-api-jaxrs/src/main/resources/META-INF/services/javax.ws.rs.ext.Providers
pom.xml

This PR depends on a release of new hawkular-parent pom, first need to merge this PR: https://github.com/hawkular/hawkular-parent-pom/pull/104
Also, it depends on one PR for alerts: https://github.com/hawkular/hawkular-alerts/pull/500 and a new release of alerts, not sure if we still need alerts for this or we can take it off.
WDYT @jsanda?

Wildfly11 update for 0.21.x

---

.travis.install.cassandra.sh

@jmartisk Could you please review?
This should solve the travis issue we are seeing in your PR:  https://github.com/hawkular/hawkular-metrics/pull/994

Fix mirror in order to get correct C* version

---

containers/hawkular-openshift-security-filter/src/main/java/org/hawkular/openshift/auth/BasicAuthenticator.java
containers/hawkular-openshift-security-filter/src/main/java/org/hawkular/openshift/auth/CreatePassword.java
containers/hawkular-openshift-security-filter/src/main/java/org/hawkular/openshift/auth/PasswordManager.java

Offer password hashing functions using SHA526, SHA512 Crypt as well as PBKDF2 versions using SHA256 and SHA512 for the OpenShift containers submodule.

Add support for  SHA526, SHA512 Crypt as well as PBKDF2 algorithms for openshift submodule
