metrics-core/src/main/java/org/rhq/metrics/impl/cassandra/MetricsServiceCassandra.java, rest-servlet/pom.xml, rest-servlet/src/main/java/org/rhq/metrics/restServlet/influx/InfluxSeriesHandler.java
* Removed dependency on EE7 managed executors API
* InfluxSeriesHandler: execute all transformations in the same thread (metricsTask thread)
* MetricsServiceCassandra: add missing "metricsTasks" specifications, remove where not needed
=> Executors usage cleanup

clients/ptranslator/pom.xml, clients/ptranslator/src/main/java/org/rhq/metrics/clients/ptrans/Main.java, clients/ptranslator/src/main/java/org/rhq/metrics/clients/ptrans/OptionsFactory.java, clients/ptranslator/src/main/java/org/rhq/metrics/clients/ptrans/PidFile.java
Added a "-p" to set the path to the PID file
ptrans will try to acquire a write lock on the PID file
Java has no built-in support for self PID so the PID is provided by
JNR (the library built by the JRuby team).
=> ptrans PID file

pom.xml
Upgrade ANTLR to avoid suspicious warning on Java 8
"Supported source version 'RELEASE_6' from annotation processor 'org.antlr.v4.runtime.misc.NullUsageProcessor' less than -source '1.8'"
See https://github.com/antlr/antlr4/issues/487
=> Upgrade ANTLR to avoid suspicious warning on Java 8

clients/ptranslator/ptrans.conf, clients/ptranslator/src/assembly/dist/assets/ptrans.conf, clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/Configuration.java, clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/ConfigurationKey.java, clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/MetricBatcher.java, clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/collectd/CollectdChannelInitializer.java, clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/ganglia/GangliaChannelInitializer.java, clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/statsd/StatsdChannelInitializer.java, clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/MetricBatcherTest.java, clients/ptranslator/src/test/resources/ptrans.conf
Ganglia, statsd and collectd sources use a metric batcher. If the data incoming rate is low and the batch size high, then ptrans might wait an arbitrary amount of time before forwarding metrics.
For example:
* collectd sending only 1 metric, one value per minute
* batch size set to 5
-> then ptrans will wait 5 minutes before sending a batch of 5 metrics
This PR introduces a batch.delay parameter in ptrans configuration file.
Now MetricBatcher class will output a list of metrics when batch.size is reached or no metric was added since (batch.delay) seconds.
=> HWKMETRICS-25 ptrans might wait an arbitrary amount of time before forwarding metrics

api/metrics-api-jaxrs/pom.xml, api/metrics-api-jaxrs/src/test/java/org/hawkular/metrics/api/jaxrs/config/ConfigurableProducerTest.java, api/metrics-api-jaxrs/src/test/java/org/hawkular/metrics/api/jaxrs/influx/query/parse/definition/InfluxTimeUnitTest.java, api/metrics-api-jaxrs/src/test/java/org/hawkular/metrics/api/jaxrs/influx/query/translate/ToIntervalTranslatorTest.java, api/metrics-api-jaxrs/src/test/java/org/hawkular/metrics/api/jaxrs/influx/query/validation/ValidationRulesProducerTest.java, api/metrics-api-jaxrs/src/test/java/org/hawkular/metrics/api/jaxrs/influx/write/validation/InfluxObjectValidationRulesProducerTest.java, clients/common/pom.xml, clients/ptranslator/pom.xml, clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/CanReadMatcher.java, clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/ConfigurationITest.java, clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/ContainsMatcher.java, clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/HasSizeMatcher.java, clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/IsFileMatcher.java, clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/MetricBatcherTest.java, clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/OpenedPortsITest.java, clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/OptionsITest.java, clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/PidFileITest.java, clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/WriteLockedMatcher.java, core/metrics-core-api/pom.xml, core/metrics-core-impl/pom.xml, pom.xml, rest-tests/pom.xml
This all started when I realized REST WAR had junit and hamcrest in WEB-INF/lib
junit has no default scope in H* parent
So now we follow H* Parent way of defining test dependencies (no default scope)
Also, removed assertj dependency (nobody's been using it other than me, I'll only miss a few features)
=> Test code updates

api/metrics-api-jaxrs/pom.xml, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/AvailabilityDataParams.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/AvailabilityDataPoint.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/BucketDataPoint.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/DataPoint.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/DataPointOut.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/IdDataPoint.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricDataParams.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricOut.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricParams.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/NumericDataParams.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/NumericDataPoint.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/PingHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/SimpleLink.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/StringValue.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/TagParams.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/TenantParams.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/TenantsHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/swagger/filter/JaxRsFilter.java, api/metrics-api-jaxrs/src/main/resources/rest-doc/asciidoc.mustache
This patch attempts to add up-to-date documentation by using swagger-annotations in our REST handlers. All the documentation options target current implementation, not how they should look like (eg. HWKMETRICS-26 is not seen in here) and will require updating once people do changes to the REST-API.
Slightly unfinished, I'm waiting to hear comments on certain parts because they're sometimes guesses on how things are working / are attempting to work.
It's also possible that generating documentation using RHQ rest-doc-generator doesn't work anymore as the swagger annotations have changed.
=> [HWKMETRICS-27] Swagger annotations

core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/cassandra/DataAccessImpl.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/cassandra/MetricsServiceCassandra.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/schema/SchemaManager.java
These fix some critical issues in other functions than REST-API. Use of entrySet instead of keySet when all the entries are iterated over and use of try-with instead of Closeable (and also fix potential resource leak at the same time).
=> SonarQube issues - try-with and entrySets

api/metrics-api-jaxrs/src/main/resources/rest-doc/asciidoc.mustache, pom.xml
This allows to delay checkstyle execution to the verify phase (instead of compile)
=> Upgrade to parent POM v9

clients/ptranslator/pom.xml
Sometimes the build fails weirdly and it seems to be because rest-tests and and ptrans use the same Wildfly ports (even though they are executed one after the other).
=> Use different ports for pTrans Wildfly integration tests server

api/metrics-api-jaxrs/pom.xml, clients/ptranslator/pom.xml, embedded-cassandra/embedded-cassandra-ear/pom.xml, pom.xml, rest-tests/pom.xml
Upgrade Wildfly Maven Plugin version -> now we can skip server start when tests are disabled
=> Wildfly Maven Plugin: skip server start when tests are disabled

core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/BucketDataPoint.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/cassandra/BucketedOutputMapper.java, rest-tests/src/test/groovy/org/hawkular/metrics/rest/CassandraBackendITest.groovy, rest-tests/src/test/groovy/org/hawkular/metrics/rest/NumericMetricStatisticsITest.groovy, rest-tests/src/test/groovy/org/hawkular/metrics/rest/RESTTest.groovy
Added median column
Also, BucketedOutputMapper no longer calls org.apache.commons.math3.stat.StatUtils.* because these methods are not thread-safe
=> HWKMETRICS-34 Added missing median column

.travis.swagger.sh, .travis.yml, api/metrics-api-jaxrs/pom.xml
This won't invoke the build of the website immediately (=> tons of builds), but once the website is built it takes this up-to-date adoc file by this script (and adds a jBake header) 
https://github.com/hawkular/hawkular.github.io/blob/pages/.travis.swagger.sh
=> Swagger documentation will be pushed to website repo after each successfull build

api/metrics-api-jaxrs/pom.xml
Use project.build.directory (build.directory notation is deprecated) for the generated stuff
=> [HWKMETRICS-40] Fix target directory for the swagger json

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/exception/mappers/BadRequestExceptionMapper.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/exception/mappers/ExceptionMapperUtils.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/exception/mappers/NotAcceptableExceptionMapper.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/exception/mappers/NotAllowedExceptionMapper.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/exception/mappers/NotFoundExceptionMapper.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/exception/mappers/NotSupportedExceptionMapper.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/exception/mappers/ReaderExceptionMapper.java, rest-tests/pom.xml, rest-tests/src/test/java/org/hawkular/metrics/test/ApiErrorJson.java, rest-tests/src/test/java/org/hawkular/metrics/test/ErrorsITest.java, rest-tests/src/test/java/org/hawkular/metrics/test/RESTTest.java
This fix handles NotAcceptable(406), NotAllowed(405), NotFound(404) and NotSupported(415) exceptions. Returns http response with error message and corresponding status code. For NotFound(404) exception only it returns status code as 400 (Bad request).
=> [HWKMETRICS-39]fix for JAX-RS warnings and send proper error message

api/metrics-api-jaxrs/pom.xml
**don't merge yet**
This can be merged once hawkular/hawkular-build-tools/pull/15 is merged and hawkular-parent version is updated. Also, I guess, the version of build-tools should be bumped.
=> HAWKULAR-134 - Moving the asciidoc.mustache to hawkular-build-tools

.travis.yml
Currently it concatenates the commands on each like in the if-then statement so it fails with https://travis-ci.org/hawkular/hawkular-metrics/builds/61045031#L2066
Adding a semicolon (no need to use &&, because we want to deploy the docs even if the mvn deploy fails). And also mvn return codes are inherently broken, it returns 0 all the time ;)
=> Fixing the travis after success section

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java, core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/MetricsService.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/cassandra/DataAccess.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/cassandra/DataAccessImpl.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/cassandra/MetricsServiceCassandra.java, core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/cassandra/DelegatingDataAccess.java, rest-tests/src/test/groovy/org/hawkular/metrics/rest/TagsITest.groovy
This will change the REST-interface to be more consistent:
GET /{id}/tags will return the tags only, instead of metric definition
GET /{id} will return the metric definition
=> HWKMETRICS-85 Tags will return only tags and definition has its own method

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/prettyprint/PrettyFilter.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/prettyprint/PrettyInterceptor.java
PrettyFilter checks if the output should be formatted and PrettyInterceptor intercepts JSON response to format it.
I've tried to find how to interact with the RestEasy Jackson mappers directly but the solution would have been hard to maintain.
Here there's a little overhead due to parsing of the entity stream. But this will only be used by humans for a fraction of requests.
=> HWKMETRICS-67 Influx endpoint: support pretty print query parameter

api/metrics-api-jaxrs/src/main/antlr4/org/hawkular/metrics/api/jaxrs/influx/query/parse/InfluxQuery.g4, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/InfluxObject.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/InfluxSeriesHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/prettyprint/PrettyFilter.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/prettyprint/PrettyInterceptor.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/query/parse/definition/SelectQueryDefinitionsParser.java, api/metrics-api-jaxrs/src/test/resources/influx/query/supported-select-queries.iql, api/metrics-api-jaxrs/src/test/resources/influx/query/syntactically-correct-queries.iql, clients/ptranslator/log4j-dev.xml, rest-tests/src/test/groovy/org/hawkular/metrics/rest/InfluxITest.groovy, rest-tests/src/test/java/org/hawkular/metrics/test/InfluxDBTest.java, rest-tests/src/test/java/org/hawkular/metrics/test/InfluxDatabaseITest.java
- Catch query parse exception so that a proper response can be built
- Use plain text error messages as Influx does
- Fixed list series output bug
- Fix pretty interceptor/filter: InfluxHandler may change the media type (for errors)
- Support absolute moment operands in queries (select * from test where time > 1501560s and time < 4560546h)
- Configure InfluxObject explicitly to include empty points collection in JSON output
Also:
- make sure Influx tests never fail because of data conflict (user distinct tenantId/dbName)
- change ptrans log level in development config file
=> Updates after Grafana integration testing

.travis.swagger.sh
there was an issue with bash `&&` `||` evaluation priority
=> REST docs weren't auto-updating, 

api/metrics-api-jaxrs/pom.xml, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/filter/TenantFilter.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/BaseHandler.java, api/metrics-api-jaxrs/src/main/webapp/WEB-INF/web.xml, rest-tests/pom.xml, rest-tests/src/test/groovy/org/hawkular/metrics/rest/RESTTest.groovy, rest-tests/src/test/groovy/org/hawkular/metrics/rest/RootITest.groovy
Add some simple data to the base endpoint instead of throwing an error.
Fix an issue where the REST tests could fail based on a race condition.
=> HWKMETRICS-117

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceProducer.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/AvailabilityBucketedOutputMapper.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/BucketedOutputMapper.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/CassandraSession.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/ComputeTTL.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/CountersMapper.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/DataAccess.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/DataAccessImpl.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/DataRetentionsMapper.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/Functions.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/GaugeAndTTL.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/GaugeBucketedOutputMapper.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/GaugeDataMapper.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/MetricsIndexMapper.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/MetricsServiceImpl.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/Order.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/Table.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/TaggedAvailabilityMapper.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/TaggedGaugeDataMapper.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/VoidSubscriber.java, core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/AvailabilityBucketDataPointMatcher.java, core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/AvailabilityBucketedOutputMapperTest.java, core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/DataAccessITest.java, core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/DelegatingDataAccess.java, core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/MetricsITest.java, core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/MetricsServiceITest.java
There is no need for a cassandra-specific package any more since we now only
support one backend.
=> [HWKMETRICS-112] move classes up one level

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/MetricsService.java
Remove default tenant id
It's no longer needed, we reject any request without tenant header (where applicable).
=> Remove default tenant id

api/metrics-api-jaxrs/src/main/antlr4/org/hawkular/metrics/api/jaxrs/influx/query/parse/InfluxQuery.g4, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/InfluxSeriesHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/query/parse/definition/ListSeriesDefinitionsParser.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/query/parse/definition/RegularExpression.java, api/metrics-api-jaxrs/src/test/java/org/hawkular/metrics/api/jaxrs/influx/query/parse/definition/ListSeriesRegexpTest.java, api/metrics-api-jaxrs/src/test/java/org/hawkular/metrics/api/jaxrs/influx/query/parse/type/QueryTypeVisitorTest.java, api/metrics-api-jaxrs/src/test/resources/influx/query/syntactically-correct-queries.iql, api/metrics-api-jaxrs/src/test/resources/influx/query/syntactically-incorrect-queries.iql, rest-tests/src/test/groovy/org/hawkular/metrics/rest/InfluxITest.groovy
Influx Grammar did not support "list series" queries with regular expression arguments like:
```
list series /cpu\.user/I
```
Grafana executes such queries to build the list series popup based on what the user typed in the "serie name" field.
=> HWKMETRICS-122 Grafana can't display metrics list popup

clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/fullstack/GraphiteITest.java
HWKMETRICS-160 Fix Intermittent test failures in GraphiteITest
When EmbeddedJMXTrans is stopped, it collects and sends metrics one last time after the schedulers have
been shut down. So two data points can have very close timestamps. But Graphite only supports second
resolution. So it is possible that two points with the same timestamp (see #getTimestamp logic) are sent
to the server. Consequently, when building the expected data set, we need to check if one metric has two
points with the same timestamp, and, in this case, keep the older one only.
=> HWKMETRICS-160 Fix Intermittent test failures in GraphiteITest

core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/MetricsServiceITest.java, rest-tests/src/test/groovy/org/hawkular/metrics/rest/CassandraBackendITest.groovy
Add missing tests for HWKMETRICS-110 to prevent regression.
The functionality was fixed as a side effect in HWKMETRICS-129 commits. Replaces older PR.
=> [HWKMETRICS-110] Add missing tests 

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/config/ConfigurationKey.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/MetricsService.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/DataAccessImpl.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/GenerateRate.java, core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/FakeTaskService.java, core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/MetricsServiceITest.java, core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/RatesITest.java, rest-tests/pom.xml, rest-tests/src/test/groovy/org/hawkular/metrics/rest/CountersITest.groovy, task-queue/src/main/java/org/hawkular/metrics/tasks/api/TaskService.java, task-queue/src/main/java/org/hawkular/metrics/tasks/impl/TaskServiceImpl.java
This PR also integrates the task scheduling service into the jaxrs WAR so that rates get calculated and updated for counter metrics.
=> Add endpoint for retrieving rates

containers/container-tests/src/test/java/org/hawkular/containers/HeapsterTest.java, containers/kubernetes/src/main/fabric8/kubernetes.json, containers/pom.xml
Add support for heapster to the kubernetes.json file and add in simple tests to make sure that heapster is able to write metrics into hawkular.
NOTE: this patch should be ready to be committed, except that it relies on a snapshot version of fabric8. Once fabric8 has its next release and the dependency updated to a non-snaphshot version, then this PR will be ready to be pulled.
=> Hwkmetrics 137

.travis.install.cassandra.sh
The installer script now determines what is the latest released version of C*. Seems to work:
https://travis-ci.org/hawkular/hawkular-metrics/builds/70040930#L210-L251
```
+wget -O datastax-releases 'http://downloads.datastax.com/community/?C=M;O=D'
--2015-07-08 10:35:23--  http://downloads.datastax.com/community/?C=M;O=D
Resolving downloads.datastax.com (downloads.datastax.com)... 54.200.218.191, 52.24.161.158, 54.186.128.156, ...
Connecting to downloads.datastax.com (downloads.datastax.com)|54.200.218.191|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: `datastax-releases'
[  <=>                                  ] 123,198      548K/s   in 0.2s    
2015-07-08 10:35:24 (548 KB/s) - `datastax-releases' saved [123198]
++cat …
```
=> Always install latest C* 2.1.x

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java, core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/MetricType.java, core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/MetricsService.java, core/metrics-core-api/src/test/java/org/hawkular/metrics/core/api/MetricTypeTest.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/DataAccess.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/DataAccessImpl.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/MetricsServiceImpl.java, core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/DelegatingDataAccess.java, core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/MetricsServiceITest.java, rest-tests/src/test/groovy/org/hawkular/metrics/rest/CassandraBackendITest.groovy, rest-tests/src/test/groovy/org/hawkular/metrics/rest/TagsITest.groovy
[HWKMETRICS-20] [HWKMETRICS-171] Allow / to fetch all the metric definitions, use tags and type as filters. Create new methods for fetching with tags.
Changes signature of fetching metric definition, missing type is no longer considered an error (and no code 400 is returned), instead all the metric definitions are returned for the tenant.
=> [HWKMETRICS-20] [HWKMETRICS-171] Ability to fetch all the metric definitions, tags and type as filters

.travis.yml, clients/ptranslator/pom.xml, clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/backend/MetricsSenderITest.java, clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/data/ServerDataHelper.java, core/metrics-core-impl/pom.xml, rest-tests/pom.xml, rest-tests/src/test/java/org/hawkular/metrics/test/InfluxDBTest.java, rest-tests/src/test/java/org/hawkular/metrics/test/RESTTest.java, task-queue/pom.xml, task-queue/src/test/java/org/hawkular/metrics/tasks/BaseITest.java, task-queue/src/test/java/org/hawkular/metrics/tasks/impl/LeaseServiceITest.java, task-queue/src/test/java/org/hawkular/metrics/tasks/impl/TaskSchedulerITest.java, task-queue/src/test/java/org/hawkular/metrics/tasks/impl/TaskServiceITest.java
Don't run integration tests by default.
Of course they will still have to run on Travis.
Each project with integration tests has its own profile, so that one can build the sources and run selected integration tests:
- "rests-tests-integration-tests"
- "ptrans-integration-tests"
- "core-impl-tests-integration-tests"
- "task-queue-integration-tests"
All these profile are activated if "-Dintegration-tests" is added to the build command.
In rests-tests and ptrans modules, developers can still use the "-Drunning.service" flag to skip Wildfly start/deploy/stop cycle.
=> HWKMETRICS-175 Put integration tests in profiles

clients/ptranslator/pom.xml, core/metrics-core-impl/pom.xml, rest-tests/pom.xml, task-queue/pom.xml
Active by default no longer used to activate itests profiles. Instead, they're active if 'skipTests' property is absent.
This fixed the other issue at the same time: we shouldn't require a running Cassandra to build Hawkular Metrics when tests are skipped.
Side work: moved wildfly config setup to 'wildfly.deployment' profile to avoid execution when it's not needed
=> HWKMETRICS-184 && HWKMETRICS-183

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/InfluxSeriesHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/util/ApiUtils.java, core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/Aggregate.java, core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/Metric.java, core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/MetricId.java, core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/MetricsService.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/DataAccess.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/DataAccessImpl.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/DataRetentionsMapper.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/GenerateRate.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/MetricsServiceImpl.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/TaggedAvailabilityDataPointMapper.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/TaggedGaugeDataPointMapper.java, core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/DataAccessITest.java, core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/DelegatingDataAccess.java, core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/MetricsServiceITest.java, core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/RatesITest.java
This PR moves the tenantId and MetricType definitions from Metric to MetricId. Metric's getTenantId()  and getType() are marked as deprecated and will return data from the assigned MetricId.
=> [HWKMETRICS-114] Refactor MetricId to include tenantId and MetricType

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java
=> Don't throw the full stack trace as it is too noisy and not needed.

rest-tests/src/test/groovy/org/hawkular/metrics/rest/BaseITest.groovy, rest-tests/src/test/groovy/org/hawkular/metrics/rest/RESTTest.groovy
The main change is in the RESTClient failure handler implementation.
There used to be a stranged exception thrown when an error response was unexpected.
Now the status line and body (if present) are printed, and tests methods assertions are executed (like assert response status == 200)
=> rest-tests minor changes

containers/README.adoc
Long arguments to OpenShift commands start with two dashes, `--`.
@mwringe
=> Use correct long argument form in containers README

.travis.yml, api/metrics-api-jaxrs-1.1/src/main/java/org/hawkular/metrics/api/jaxrs/handler/VirtualClockHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/VirtualClockHandler.java, rest-tests/pom.xml, tests/rest-integration-tests-jaxrs-1.1/pom.xml
Some REST API tests have been periodically failing on travis builds because of
the timeout value for TestSubscriber.awaitTerminalEvent() being too low in
VirtualClockHandler. This commit makes it configurable via a system property
and increases the timeout for travis builds to 25 seconds.
=> make terminal event timeout in REST API tests configurable

api/metrics-api-jaxrs-1.1/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java, core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/MetricsService.java, core/metrics-core-impl/pom.xml, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/DataAccessImpl.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/MetricsServiceImpl.java, core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/MetricsITest.java, core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/MetricsServiceITest.java, rest-tests/src/test/groovy/org/hawkular/metrics/rest/CountersITest.groovy, rest-tests/src/test/groovy/org/hawkular/metrics/rest/MetricsITest.groovy, rest-tests/src/test/groovy/org/hawkular/metrics/rest/TenantITest.groovy
This commit also removes most of the code around scheduled task execution,
which includes the tasks for generating creates and creating tenants. The
latter is no longer neeed with the work done in HWKMETRICS-190.
=> [HWKMETRICS-228] calculate rates at query time

README.adoc, clients/ptranslator/pom.xml, rest-tests/pom.xml
Some properties still present in ptrans itest config no longer exist in REST module.
By default, keep test server file logging to a minimum (like CONSOLE level).
Update README to precise on Wildfly version to download.
=> Minor POM and doc changes.

api/diff.txt, api/metrics-api-common/src/main/java/org/hawkular/metrics/api/jaxrs/util/MetricTypeTextConverter.java, api/metrics-api-jaxrs-1.1/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java, api/metrics-api-jaxrs-1.1/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, api/metrics-api-jaxrs-1.1/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java, api/metrics-api-jaxrs-1.1/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/jackson/MetricTypeDeserializer.java, rest-tests/src/test/groovy/org/hawkular/metrics/rest/CassandraBackendITest.groovy
Adds a generic (to /metrics) endpoint with the ability to create a metric definition by defining the type in the payload. Also fix a bug in HWKMETRICS-232 PR (deserialization, added test to prevent regression) and add type checks to type specific handlers
=> [HWKMETRICS-233] Add REST-endpoint to creating any type metric definitions

core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/Aggregate.java
HWKMETRICS-250 Core-API does not compile on newest JDK 1.8
Helped the compiler to infer generic type
=> HWKMETRICS-250 Core-API does not compile on newest JDK 1.8

api/metrics-api-common/src/main/resources/META-INF/beans.xml
Exclude Jackson utility classes from CDI scans
This is to avoid warnings (classes not available) on EAP6.4 during deployment
=> Exclude Jackson utility classes from CDI scans

api/diff.txt, api/metrics-api-jaxrs/src/main/antlr4/org/hawkular/metrics/api/jaxrs/influx/query/parse/InfluxQuery.g4, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/HawkularMetricsRestApp.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/InfluxSeriesHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/InfluxTimeUnit.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/param/ConvertersProvider.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/param/InfluxTimeUnitConverter.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/query/parse/definition/GroupByClause.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/query/parse/definition/LongFunctionArgument.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/query/parse/definition/LongOperand.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/query/parse/definition/MomentOperand.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/query/parse/definition/OperandUtils.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/query/parse/definition/SelectQueryDefinitionsParser.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/query/translate/ToIntervalTranslator.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/query/validation/SimpleTimeRangesOnlyRule.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/write/validation/DataTypesRule.java, api/metrics-api-jaxrs/src/test/java/org/hawkular/metrics/api/jaxrs/influx/InfluxTimeUnitTest.java, api/metrics-api-jaxrs/src/test/java/org/hawkular/metrics/api/jaxrs/influx/param/InfluxTimeUnitConverterTest.java, api/metrics-api-jaxrs/src/test/java/org/hawkular/metrics/api/jaxrs/influx/query/parse/definition/SelectQueryColumnDefinitionsTest.java, api/metrics-api-jaxrs/src/test/java/org/hawkular/metrics/api/jaxrs/influx/query/parse/definition/SelectQueryGroupByClauseTest.java, api/metrics-api-jaxrs/src/test/java/org/hawkular/metrics/api/jaxrs/influx/query/parse/definition/SelectQueryWhereClauseTest.java, api/metrics-api-jaxrs/src/test/resources/influx/query/supported-select-queries.iql, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/InfluxITest.groovy
This PR implements "HWKMETRICS-65 Influx endpoint: add suport for timestamp precision query parameter" and fixes some issues for better Grafana compatibility:
- Avoid integer "overflow"
The parser used to store time amounts into int variables. This led to parsing errors if a time range operand was too far in the past.
- In where clause, absolute and relative time operands might have no time unit
The parser used to support explicit time units only, but the in the query language spec (aka the online manual) it is allowed to omit it.
=> More Grafana compatibility fixes and HWKMETRICS-65

core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/DataAccess.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/DataAccessImpl.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/transformers/BatchStatementTransformer.java, core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/DelegatingDataAccess.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/TagsITest.groovy
HWKMETRICS-252 Warning about batch size threshold in the logs
Reduced the number of statements per batch.
Also, removed unused method and batch statement usage where not needed.
=> HWKMETRICS-252 Warning about batch size threshold in the logs

api/diff.txt, api/metrics-api-common/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java
NPE when app is deployed but Session is not created
If Metrics has been started but Cassandra is not up, the Session object
is never created. Then, if you stop Metrics, you get an NPE.
=> NPE when app is deployed but Session is not created

CONTRIBUTING.adoc, task-queue/src/main/java/org/hawkular/metrics/tasks/impl/TaskSchedulerImpl.java
Do not use primitive arguments in logging methods calls.
=> HWKMETRICS-274 Missing JBoss logging method on EAP6.4

api/metrics-api-common/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java
While working on another driver issue today,
I realized that we do not need to call cluster#close if cluster init fails.
So I've changed #createSession method a bit to call cluster#close only when necessary.
=> Close C* cluster only when session creation fails

api/metrics-api-common/src/main/java/org/hawkular/metrics/api/jaxrs/param/Percentiles.java, api/metrics-api-jaxrs-1.1/src/main/java/org/hawkular/metrics/api/jaxrs/HawkularMetricsRestApp.java, api/metrics-api-jaxrs-1.1/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, api/metrics-api-jaxrs-1.1/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java, api/metrics-api-jaxrs-1.1/src/main/java/org/hawkular/metrics/api/jaxrs/param/PercentilesConverter.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/param/ConvertersProvider.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/param/PercentilesConverter.java, core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/MetricsService.java, core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/NumericBucketPoint.java, core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/Percentile.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/MetricsServiceImpl.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/NumericDataPointCollector.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/PercentileWrapper.java, core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/MetricsServiceITest.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CountersITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/GaugeMetricStatisticsITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/RESTTest.groovy
This allows requesting different percentile than 95th to be calculated when requesting buckets. The REST API changes from `percentile95th` -> `percentile` parameter and the new query parameter is called `percentile` (with a default value of 95.00 for old use-cases).
This is necessary for the Initial Resources implementation (it needs configurable percentile), although I'd almost want to see following:
`?buckets=1&percentiles=90,99,99.9` returning:
```javascript
"percentiles": {
"90": 0.0
"99": 0.0
"99.9": 0.0
}
```
=> Change percentile95th -> percentile and add percentile query parameter

api/metrics-api-common/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java, api/metrics-api-common/src/main/java/org/hawkular/metrics/api/jaxrs/ServiceReady.java, core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/MetricsService.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/MetricsServiceImpl.java, core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/MetricsServiceITest.java, hawkular-component/pom.xml, hawkular-component/src/main/java/org/hawkular/metrics/component/publish/AvailDataMessage.java, hawkular-component/src/main/java/org/hawkular/metrics/component/publish/AvailDataPublisher.java, hawkular-component/src/main/java/org/hawkular/metrics/component/publish/InsertedDataSubscriber.java, hawkular-component/src/main/java/org/hawkular/metrics/component/publish/MetricDataMessage.java, hawkular-component/src/main/java/org/hawkular/metrics/component/publish/MetricDataPublisher.java, hawkular-component/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, hawkular-component/src/test/groovy/org/hawkular/metrics/component/bus/test/InsertedDataITest.groovy, hawkular-component/src/test/resources/logback-test.xml, pom.xml
HWKMETRICS-83 Create glue code component to integrate with hawkular-bus
This pull request is comprised of three commits.
* Implement an InsertedDataPoint event stream
The MetricsService interface now exposes an #insertedDataEvents method. The method returns a hot Observable emitting Metric objects, when their data has been succesfully inserted.
Clients can subscribe to this Observable (preferably on a dedicated scheduler!) and they will get notified.
* Fire @ServiceReady event when MetricsService is initialized
The Metrics JAX- RS module now fires a CDI @ServiceReady event.
This event can be observed by a "super"-module in order to know when the MetricsService instance is initialized.
The event is fired just before the MetricsServiceLifecycle status changes to "STARTED", so that clients …
=> HWKMETRICS-83 Create glue code component to integrate with hawkular-bus

hawkular-component/src/main/java/org/hawkular/metrics/component/publish/AvailDataPublisher.java, hawkular-component/src/main/java/org/hawkular/metrics/component/publish/InsertedDataSubscriber.java, hawkular-component/src/test/groovy/org/hawkular/metrics/component/bus/test/InsertedDataITest.groovy
HWKMETRICS-315 Bus integration: events randomly or never posted
When Metrics was started after the Pinger, the Pinger would accumulate data to post before sending it all at once eventually.
Because there were not enough threads to handle the peak load, RxJava tried to apply backpressure but PublishSubject does not support it by nature.
The fix consists in:
- buffering inserted metric to avoid submitting too much to the #io scheduler
- adding a buffer-on-backpressure strategy
Note that the problem was emphasized before as we used to schedule sending on a wrapped ManagedExecutorService. Now we use the #io scheduler (change already in master).
I've successfully tested the changes on Hawkular server.
=> Hawkular bus integration fixes

core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/NumericBucketPoint.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/NumericDataPointCollector.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/SumNumericBucketPointCollector.java, core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/MetricsServiceITest.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CountersITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/GaugeMetricStatisticsITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/RESTTest.groovy
Removes the old 95th percentile calculation, use the percentiles instead to calculate the necessary percentiles.
=> [HWKMETRICS-313] Remove the hardcoded 95th percentile calculation

api/diff.txt, api/metrics-api-jaxrs/src/main/antlr4/org/hawkular/metrics/api/jaxrs/influx/query/parse/InfluxQuery.g4, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/query/parse/definition/SelectQueryDefinitionsParser.java, api/metrics-api-jaxrs/src/test/java/org/hawkular/metrics/api/jaxrs/influx/query/parse/definition/SelectQueryGroupByClauseTest.java, api/metrics-api-jaxrs/src/test/resources/influx/query/syntactically-correct-queries.iql, api/metrics-api-jaxrs/src/test/resources/influx/query/syntactically-incorrect-queries.iql
HWKMETRICS-322 InfluxDB API: groupby should accept milliseconds unit
Updated the grammar and tests. I thought ms were not accepted in groupby clause, as indicated in the documentation:
https://influxdb.com/docs/v0.8/api/query_language.html#group-by
But running the query on a real Influx server shows that it is supported.
=> HWKMETRICS-322 InfluxDB API: groupby should accept milliseconds unit

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/InfluxSeriesHandler.java, core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/MetricTypeFilter.java, core/metrics-core-api/src/main/java/org/hawkular/metrics/core/api/MetricsService.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/DataAccess.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/DataAccessImpl.java, core/metrics-core-impl/src/main/java/org/hawkular/metrics/core/impl/MetricsServiceImpl.java, core/metrics-core-impl/src/test/java/org/hawkular/metrics/core/impl/DelegatingDataAccess.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/InfluxITest.groovy
* Updated the "list series" handler so that it returns gauges with the "gauge." prefix and counters with the "counter." prefix.
* Updated the query handler so that it looks at the series name for a known prefix ("gauge." or "counter."); if there's no prefix, it will assume it's a gauge
* Updated the POST handler as well
* Removed old (and buggy) method: DataAccess#findAllGaugeMetrics
* Introduced MetricTypeFilter, to use with Observable#compose
=> HWKMETRICS-66 Influx endpoint: use series name prefix to match a counter or a gauge

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/influx/InfluxSeriesHandler.java
%d cannot be used with double values, the call ends with a runtime exception thrown by String#format
=> Fix Influx handler log issue (%d used with double value)

api/metrics-api-jaxrs-1.1/src/main/java/org/hawkular/metrics/api/jaxrs/param/TagsConverter.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/param/TagsConverter.java, core/metrics-model/src/main/java/org/hawkular/metrics/model/param/Tags.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/TagsITest.groovy
Allows tags with ":" "/" and equal to be queried as long as they're encoded correctly in the URL. @tsegismont You had prevented this in the past in the Tags, any particular reason? I think it would get caught in the TagsConverter already as the splitting would fail / give empty value.
=> [HWKMETRICS-333] Add support for encoded tag queries

api/diff.txt, api/metrics-api-jaxrs-1.1/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CountersITest.groovy
/counters/rate path is now aligned with the path for rate queries with specified metric id.
=> [HWKMETRICS-332] Fix the path for multi-counter rate queries

.travis.yml, bus/pom.xml, bus/src/test/java/org/hawkular/bus/PublishDataPointsTest.java
This commit also modifies the travis configuration slightly by setting the
travis system property in order to activate a profile for travis builds.
See http://goo.gl/cVf6uI for details.
=> do not hard code dependency versions in arquillian tests

bus/pom.xml, hawkular-component/pom.xml, pom.xml
Based on prior discussions (which I had forgotten about) we agreed to keep the
wildfly bom out of the parent pom. Putting it in the parent pom forces artifact
versions for all sub-modules, including those not meant to run on WildFly. In
the past this has broken the build.
=> remove wildfly bom from parent pom

integration-tests/rest-tests-jaxrs/pom.xml
It's no longer needed to build the rest-tests tests JAR (it used to be useful to run the suite against a JAX-RS 1.1 server)
=> Don't build the rest-tests tests JAR

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/filter/CorsRequestFilter.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/filter/MetricsServiceStateFilter.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/filter/TenantFilter.java, hawkular-component/src/main/java/org/hawkular/metrics/security/PersonaFilter.java
Some filters should be pre-matching filters: they should be applied very early in the request processing pipeline
=> Some filters should be pre-matching filters

hawkular-component/src/main/java/org/hawkular/metrics/security/PersonaFilter.java, hawkular-component/src/main/webapp/WEB-INF/web.xml, integration-tests/hawkular-server-tests/src/test/groovy/org/hawkular/metrics/AuthenticationITest.groovy
HWKMETRICS-346 Fix bogus Hawkular Component security rules
Do not use declarative security in web.xml.
Note that the REST endpoints are still all secured by default, only a couple are white-listed for free access.
=> HWKMETRICS-346 Fix bogus Hawkular Component security rules

core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/GenerateRateITest.java
generateRates in GenerateRateITest is failing.
It calls generateRate at first and then invoke findRateData.
It seems recalculate and overwrite the rate.
This commit just makes the test pass.
=> HWKMETRICS-348

integration-tests/hawkular-server-tests/pom.xml, integration-tests/hawkular-server-tests/src/main/resources/standalone.xsl, integration-tests/hawkular-server-tests/src/test/groovy/org/hawkular/metrics/AuthenticationITest.groovy, integration-tests/hawkular-server-tests/src/test/groovy/org/hawkular/metrics/BaseITest.groovy, integration-tests/hawkular-server-tests/src/test/groovy/org/hawkular/metrics/NewDataListenerITest.groovy, integration-tests/hawkular-server-tests/src/test/resources/logback-test.xml
HWKMETRICS-352 Add integration tests to metric input from the bus
Configured the input queues and inserted data topics to be accessible to remote clients
The integration test connects as a remote client, sends input data and listens to inserted data.
Inserted data events must match input data.
=> HWKMETRICS-352 Add integration tests to metric input from the bus

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java, clients/ptranslator/ptrans.conf, clients/ptranslator/src/assembly/dist/assets/ptrans.conf, clients/ptranslator/src/main/java/org/hawkular/metrics/clients/ptrans/Configuration.java, clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/backend/MetricsSenderITest.java, clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/data/ServerDataHelper.java, clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/fullstack/FullStackITest.java, clients/ptranslator/src/test/resources/ptrans.conf, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/AvailabilityITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/AvailabilityMetricStatisticsITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/BaseITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CORSITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CassandraBackendITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CountersITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/ErrorsITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/GaugeMetricStatisticsITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/GaugesITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/MetricsITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/RESTTest.groovy
/data endpoint became too complex to maintain since it was serving two purposes (retrieve raw and statistical data). This is also confusing to users because the decision as to what data to return was made at runtime based on the parameters.
Here are the changes in this commit:
- all /data APIs have been deprecated
- POST /data has been moved to POST /raw
- GET $id/data has been split into two
- $id/raw - to retrieve raw data
- $id/stats - to retrieve bucketed/statistical data
- Documentation for deprecated APIs has been updated to point to the new APIs.
=> [HWKMETRICS-24] 

core/schema/src/main/resources/org/hawkular/schema/bootstrap.groovy, pom.xml
This PR refactors the bootstrap.groovy script to use the new cassalog script helper functions that abstract away the logic for dealing with both Cassandra 2.x and 3.x. With these changes, we can now run against Cassandra 3.x.
=> HWKMETRICS-376

core/metrics-model/src/main/java/org/hawkular/metrics/model/Metric.java
Allow Metric deserializer to take tenant id as parameter; default value to "" if null. The existing constructor has been moved to a simple constructor, while the default behavior of the JsonCreator constructor has not changed.
=> [HWKMETRICS-378] 

api/metrics-api-common/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java, api/metrics-api-common/src/main/java/org/hawkular/metrics/api/jaxrs/config/ConfigurationKey.java
A new config property has been added. It is called DATA_GC_GRACE_SECONDS. At start up we query the system tables to get the current value of gc_grace_seconds for the data table. If the current value does not match the config value, which defaults to 1 day, we update gc_grace_seconds.
=> [BZ 1316275] add support for altering gc_grace_seconds in data table

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CORSITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/MetricsITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/TenantITest.groovy
This is the last '/data' endpoint that was not updated to the new '/raw' & '/stats' model.
=> [HWKMETRICS-24] Migrate the mixed metrics insertion POST to /raw.

api/metrics-api-jaxrs/src/main/webapp/static/index.html, api/metrics-api-jaxrs/src/main/webapp/static/welcome.css
Use leading double-slash to inherit the protocol from the webpage
Also, fixed a missing semicolon and removed import from CSS to let the browser load CSS resources in parallel (instead of waiting for the welcome CSS to be loaded).
=> HWKMETRICS-388 Allow the status page to be loaded over https without errors

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/util/ApiUtils.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsService.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java
The combination of Optional + Observable is useless as there's nothing extra the Optional could present in this case. This removes it and cleans up the code.
=> Refactor getMetricTags to remove use of Optional

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsService.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/MetricsServiceITest.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/TagsITest.groovy
This feature adds the ability to fetch only the tag values (ignoring metric definitions) using the same tag-query-language that we have currently in the metric definition fetching.
WIP: Missing REST-tests, I'm suggesting @Path("/tags/{tags}") (for all types separately and then in the metrics for fetching all the metrics)
=> [HWKMETRICS-197] Add ability to fetch tag values

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/param/ConvertersProvider.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/param/OrderConverter.java, api/metrics-api-jaxrs/src/main/rest-doc/base.adoc, api/metrics-api-jaxrs/src/test/java/org/hawkular/metrics/api/jaxrs/param/OrderConverterTest.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/Order.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CassandraBackendITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CountersITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/GaugesITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/RootITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/StatusITest.groovy
Added new converter and updated enum.
Also, updated two tests which must not run when not in a Maven build
=> HWKMETRICS-389 Endpoints that use the order param should accept lower case values

integration-tests/rest-tests-jaxrs/pom.xml, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CORSITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CountersITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/GaugeMetricStatisticsITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/InfluxITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/RESTTest.groovy
CORSITest is now ignored if run out of the Maven build (avoid failures in IDE due to missing Maven property)
RESTClient configured to use Jackson instead of JSON-lib. Jackson has configurable deserialization and allows to force conversion to BigDecimal (which works nice with floating literals in Groovy)
=> rest-tests enhancements

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/TenantsHandler.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccess.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccessImpl.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsService.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/DataAccessITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/DelegatingDataAccess.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/GenerateRateITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/MetricsServiceITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/RatesITest.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CassandraBackendITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/RESTTest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/TagsITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/TenantITest.groovy
Update metrics creation to allow users to overwrite previously created metric definitions. The flag defaults to false and is not required.
=> [HWKMETRICS-148]

api/metrics-api-jaxrs/pom.xml, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/param/ConvertersProvider.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/param/TagNamesConverter.java, api/metrics-api-jaxrs/src/test/java/org/hawkular/metrics/api/jaxrs/param/InvalidTagNamesConverterTest.java, api/metrics-api-jaxrs/src/test/java/org/hawkular/metrics/api/jaxrs/param/TagNamesConverterTest.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsService.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/MetricsServiceITest.java, core/metrics-model/src/main/java/org/hawkular/metrics/model/param/TagNames.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/TagsITest.groovy, pom.xml
HWKMETRICS-385 Deleting tags should only require the tag keys and not the values
Added a new JAX-RS param class. It allows to map a list of plain names mixed with name:value pairs (for backwared compatibility)
Updated the core service implementation so that tag values are loaded and from metric index. This is needed otherwise we can't delete rows from the tags index table (tvalue is part of the primary key).
=> HWKMETRICS-385 Deleting tags should only require the tag keys and not the values

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/TagsITest.groovy
Adds the generic "/metrics/tags/{tags}" endpoint to fetch tag values. This extends the HWKMETRICS-197 implementation.
=> Add untyped generic endpoint for tagValues fetching

clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/backend/MetricsSenderITest.java, clients/ptranslator/src/test/java/org/hawkular/metrics/clients/ptrans/data/ServerDataHelper.java
Do not fail the test if ServerDataHelper receives 204 No content. Give the test a chance to complete later.
Also, fail MetricsSenderITest if data size does not match expected data after ten pause-and-try cycles
=> HWKMETRICS-397 Intermittent failure in ptrans tests on Travis

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsService.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/Order.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/PatternUtil.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/transformers/NumericBucketPointTransformer.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/transformers/NumericDataPointCollector.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/transformers/TaggedBucketPointTransformer.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/transformers/TaggedDataPointCollector.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/GenerateRateITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/MetricsServiceITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/RatesITest.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CountersITest.groovy
I added a method in Order.java which factors out the logic to determine a default order. I updated the considering endpoints.
I change the get rate endpoint to support the new parameters. While its bucket parameters are deprecated and not removed, we need to check that they can't be set if order and limit are.
While updating the code in MetricsServiceImpl to adapt to the new  findRate signature, I extracted the code of #bucketize methods and created separated Transformer classes. Using these transformers with #compose is a more natural RxJava construct.
=> HWKMETRICS-390 Endpoint for fetching rate data points need to support standard query params and sort behavior

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/transformer/MinMaxTimestampTransformer.java, core/metrics-model/src/main/java/org/hawkular/metrics/model/Metric.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/AvailabilityITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CORSITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CassandraBackendITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CountersITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/GaugesITest.groovy
Added a MinMaxTimestampTransformer which loads min and max timestamp for each metric in a sequence.
Applied the transformer to all endpoints fetching metric definitions.
=> HWKMETRICS-383 Allow fetch min and max timestamp for a metric

hawkular-component/src/main/java/org/hawkular/metrics/component/MetricsJNDIPusblisher.java
Bind metrics service to JNDI so other hawkular components can use inject it.
@jsanda @burmanm could you please review?
=> Bind metrics service to JNDI

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsService.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java, core/metrics-model/src/main/java/org/hawkular/metrics/model/MetricType.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CountersITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/GaugesITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/RESTTest.groovy
Added rate related endpoints to GaugeHandler
Added GAUGE_RATE internal type (also, added missing STRING type to the "all" set in MetricType)
Changed MetricsService API so that rate and rate stats work on Metric<? extends Number> instead of Metric<Long>
Updated multiple metric stats algorithms to support GAUGE_RATE
=> HWKMETRICS-365 Support rate data for gauge metrics

integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CountersITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/GaugeMetricStatisticsITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/RESTTest.groovy
Add integration tests to verify empty buckets are returned with zero values. The functionality has been fixed in previous releases. This PR just adds integration tests.
=> [HWKMETRICS-345]

hawkular-component/src/main/webapp/WEB-INF/web.xml
/status and /static no longer require authentication.
=> HWKMETRICS-401

containers/hawkular-metrics-openshift-integration/src/main/java/org/hawkular/openshift/auth/TokenAuthenticator.java
As advised by the Undertow dev team, use UndertowXnioSsl instead of the default Xnio implementation. UndertowXnioSsl is the only implementation which the Wildfly team uses for testing.
=> HWKMETRICS-408 Buffer was already freed error

hawkular-component/pom.xml
When Metrics was integrated with Accounts, the CORS filters were removed
because CORS had to be managed by Keycloak.
Now that Accounts is removed, we must add them back, otherwise we can't
send CORS requests to Metrics.
=> HWKMETRICS-412 Add CORS filters back to hawkular component

integration-tests/jmh-benchmark/pom.xml, integration-tests/jmh-benchmark/run.sh, integration-tests/jmh-benchmark/src/main/java/org/hawkular/metrics/benchmark/jmh/InsertBenchmark.java, integration-tests/jmh-benchmark/src/main/java/org/hawkular/metrics/benchmark/jmh/util/ClusterManager.java, integration-tests/jmh-benchmark/src/main/java/org/hawkular/metrics/benchmark/jmh/util/LiveCassandraManager.java, integration-tests/jmh-benchmark/src/main/java/org/hawkular/metrics/benchmark/jmh/util/MetricServiceManager.java, integration-tests/jmh-benchmark/src/main/java/org/hawkular/metrics/benchmark/jmh/util/MockCassandraManager.java, integration-tests/jmh-benchmark/src/main/java/org/hawkular/metrics/benchmark/jmh/util/SCassandraManager.java, integration-tests/pom.xml
This PR creates JMH based benchmarking setups to assist in finding the bottlenecks. Completely skips the REST-layer, JSON transformations and runtime (Wildfly), instead writing directly to the core-service.
The output looks like:
```
Benchmark                              (datapointsPerMetric)  (size)  Mode  Cnt   Score   Error  Units
InsertBenchmark.insertBenchmark                            1  100000  avgt   10   4.489 ± 0.193   s/op
InsertBenchmark.insertBenchmark                           10  100000  avgt   10   8.655 ± 3.612   s/op
InsertBenchmark.insertBenchmarkSingle                      1  100000  avgt   10   8.881 ± 2.360   s/op
InsertBenchmark.insertBenchmarkSingle                     10  100000  avgt   10  11.152 ± 2.108   s/op
```
The Scassandra implementation and Mockito …
=> Add JMH benchmarking capabilities

core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java, integration-tests/jmh-benchmark/pom.xml, integration-tests/jmh-benchmark/src/main/java/org/hawkular/metrics/benchmark/jmh/InsertBenchmark.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CountersITest.groovy
Use mergeWith instead of concat and map the result to null as we don't use it at the moment. On my machine this improved the benchmark writes by about 10% (not including JAX-RS layer).
Also replace the test Observable.create with Observable.from(list) as it reduces the impact of test. Added support for JMC (Java Mission Control) profiler. Also the test uses now Netty native epoll on linux-x86_64, this further improves the performance by another 5-10% by reducing the CPU load of Cassandra driver (we should probably consider using this elsewhere also).
=> HWKMETRICS-417 Improve performance of write path

bus/src/test/java/org/hawkular/bus/PublishDataPointsTest.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/AvailabilityDataPointCollector.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/AvailabilityBucketPointMatcher.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/AvailabilityDataPointCollectorTest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/AvailabilityITest.java, core/metrics-model/src/main/java/org/hawkular/metrics/model/AvailabilityBucketPoint.java, core/metrics-model/src/main/java/org/hawkular/metrics/model/AvailabilityType.java
- Add ADMIN as avail value=3
- Needed to refactor AvailabilityBucketPoint
- this was flawed as it assumed only UP and DOWN avail, ignoring UNKNOWN
and now ADMIN.
- this is publicly exposed via JSON in the GET avail REST endpoints
- Kept as deprecated some obsolete fields for JSON back compatibility
- ??? One question for reviewers: Is it OK to now expose a Map in the
JSON or do you prefer replacing the map with explicit fields ???
@stefannegrea and/or @jsanda please review.
=> HWKMETRICS-420 Add ADMIN AvailabilityType

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java
This gets around an issue where users can see an 'unknown error' message in the logs when the Cassandra hostname could not be resolved.
Updates the log message to make it a bit more user friendly
=> Gets around the 'unknown error' message in the log

core/metrics-core-service/pom.xml, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/BaseITest.java, core/schema/src/main/resources/org/hawkular/schema/bootstrap.groovy, pom.xml
There were a couple bugs in cassalog that broke upgrades. I have fix and
released a new version of cassalog. This commit bumps the cassalog version and
also fixes a couple issues in bootstrap.groovy. Lastly,I have made resetting
schema during integration tests in metrics-core-service optional with the
resetdb system property which expects a value of true or false.
=> [HWKMETRICS-425] fix schema upgrade bugs

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/observer/NamedDataPointObserver.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/GaugesITest.groovy
Fixed no data for query case.
A couple of side changes:
- the observer might run on different threads so make fields final when possible and volatile otherwise
- simplified writeValue lambda form by using a dedicated functional interface
=> HWKMETRICS-427 JsonGenerationException: Current context not an object but ROOT

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/param/PercentilesConverter.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsService.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/transformers/NumericBucketPointTransformer.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/transformers/NumericDataPointCollector.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/transformers/TaggedBucketPointTransformer.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/transformers/TaggedDataPointCollector.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/BaseITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/BaseMetricsITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/CounterITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/RatesITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/TagsITest.java, core/metrics-model/src/main/java/org/hawkular/metrics/model/Percentile.java, core/metrics-model/src/main/java/org/hawkular/metrics/model/param/Percentiles.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CountersITest.groovy
Change percentile queries to return the original requested value instead of calculated value from PSPercentile (from apache.commons.math). This prevents client from having to deal with floating point imprecision in quantile keys.
=> [HWKMETRICS-426] Change Percentiles to return original percentile

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/filter/MetricsServiceStateFilter.java
Do not abort status page request if status is not "STARTED"
=> HWKMETRICS-432 Status page cannot be displayed when status is not "STARTED"

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/BaseHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricsServiceHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/PingHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/StatusHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/StringHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/TenantsHandler.java
Please do not merge yet.
Thinking about performance, using singleton JAX-RS handlers will reduce GC pressure.
Currently, a handler class instance is created for every request.
I would like to see if this as an impact on Filip's tests.
I had to remove @HeaderParam annotation as they are not available in singleton handlers.
=> Use singleton JAX-RS handlers

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/IMetricsHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/StringHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/template/IMetricsHandler.java
Create a basic interface for JAXRS handlers for methods like creating, listing, and adding data to metrics.
I created [HWKMETRICS-435](https://issues.jboss.org/browse/HWKMETRICS-435) to track implementing 'fromEarliest' for `/raw` endpoints for gauge and counter. Somehow this was missed during the migration away from `/data`.
=> [HWKMETRICS-440] Create Interface for JAXRS Handlers

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricsServiceHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/StringHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/observer/NamedDataPointObserver.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/template/IMetricsHandler.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/GaugesITest.groovy
This implementation solves two issues:
1. it does not need to block a task handler thread until the response is fully sent
2. it allows to defer response code setup to the NamedDataPointObserver,
thus allowing meaningful response codes (204, 500)
=> Servlet based JSON streaming implementation

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/StatsQueryRequest.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java, core/metrics-model/src/main/java/org/hawkular/metrics/model/AvailabilityBucketPoint.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/MetricsITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/RESTTest.groovy
This PR adds an endpoint for fetching stats (i.e., bucket data points) from multiple metrics in a single request. Right now it only supports gauges and counter. I will update the endpoint to also support gauge and counter rate stats as well. I wanted to go ahead submit the PR for review though because adding support for rates is mostly boiler plate along with additional integration tests.
@lucasponce would it make sense to include availability stats as well?
=> [HWKMETRICS-424] Fetch stats from multiple metrics in a single request

job-scheduler/src/main/java/org/hawkular/metrics/scheduler/api/RetryPolicy.java, job-scheduler/src/main/java/org/hawkular/metrics/scheduler/api/Scheduler.java, job-scheduler/src/main/java/org/hawkular/metrics/scheduler/impl/SchedulerImpl.java, job-scheduler/src/test/java/org/hawkular/metrics/scheduler/impl/JobExecutionTest.java
A retry policy specifies if and when a job should be retried in the event of a
failure. Retry policies are effective only for non-repeating jobs. If a
repating job fails, its trigger determines when it executes again. By default,
failed jobs will not be retried.
=> [HWKMETRICS-453] add retry policy for non-repeating jobs

containers/hawkular-metrics-openshift-integration/src/main/java/org/hawkular/openshift/auth/TokenAuthenticator.java
The POST endpoint /counters/rate/query is used to read data, it should be authorized for read-only users (similar to /counters/raw/query)
=> Allow rate queries for read-only users

containers/hawkular-metrics-openshift-integration/src/main/java/org/hawkular/openshift/auth/TokenAuthenticator.java
The POST endpoint /counters/rate/query is used to read data, it should be authorized for read-only users (similar to /counters/raw/query)
(cherry picked from commit 7082face66026ad6eb4d3cafc24b0ebd4bf4f065)
=> [HWKMETRICS-460] Allow rate queries for read-only users

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/DriverUsageMetricsManager.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java
Previously driver usage was printed regularly in the logs.
With this change, driver usage metrics will be publish to the registry.
=> HWKMETRICS-439 Create driver usage metrics

core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccess.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccessImpl.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsService.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/transformers/MetricFromDataRowTransformer.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/transformers/MetricFromFullDataRowTransformer.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/DelegatingDataAccess.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/AvailabilityITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/BaseMetricsITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/GaugeITest.java
Avoid writing to the metrics index on data point inserts. However, keep all the other writes to the metrics index in place.
Here are the changes to query metrics:
1) When requesting info about a single metric
a) query the metrics index first, if found then return the info (just like before this change)
b) if no result there, query the data table for a single data point, if found then the metric exists just not in the metrics index
c) if no result in either metrics index or data table then there is no such metric
2) When requesting a list of all metrics for a tenant
a) query the metrics index first
b) query the data table for all metrics and filter by tenant and type if needed
c) concat the two lists
d) return only distinct values; note that the results from metrics index take precendence …
=> [HWKMETRICS-422] Avoid writing to the metrics index on data point inserts

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java
Swagger annotations dont match what is actually returned, which is confusing when parsing back to objects via jackson
=> Updated swagger return types to match actual return types

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/TagsITest.groovy
The regexp was missing double quotation for the regexp character "|", that's why it returned incorrect information. Also the tests used the wrong endpoint and just happened to work.
=> [HWKMETRICS-461] Fix the regexp split

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/QueryRequest.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricsServiceHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/StringHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/param/TagsConverter.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsService.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/AvailabilityITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CountersITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/GaugesITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/StringITest.groovy
Following discussion "[Hawkular-dev] metrics: REST API evolution when querying for multiple metrics" on the mailing list
See also https://issues.jboss.org/browse/HWKMETRICS-466
=> [HWKMETRICS-466] Add query by tags capability to /query endpoints

pom.xml
Cassalog 0.3.0 changes the default behavior of the setKeyspace function to always run. This should address the problems encountered in HWKMETRICS-483.
=> [HWKMETRICS-483] bump cassalog version

job-scheduler/src/main/java/org/hawkular/metrics/scheduler/impl/LockManager.java, job-scheduler/src/main/java/org/hawkular/metrics/scheduler/impl/SchedulerImpl.java, job-scheduler/src/test/java/org/hawkular/metrics/scheduler/impl/JobExecutionTest.java
If a job runs long and misses its next execution time, the scheduler will now
execute the job again immediately for the missed execution. It will do so until
the job is caught up.
=> [HWKMETRICS-477] reschedule job for immediate execution if it falls behind

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/AggregatedStatsQueryRequest.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricsServiceHandler.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/GaugeMetricStatisticsITest.groovy
It's a kind of duplication of the GET endpoints "gauges/stats" and "counters/stats".
The reason is the same as the one explained here: https://issues.jboss.org/browse/HWKMETRICS-410 and which ended up in duplicating GET "gauges/raw" endpoint to POST "gauges/raw/query" in a similar way.
Also added integration tests
=> [HWKMETRICS-465] New POST endpoints gauges/stats/query and counters/stats/query

job-scheduler/pom.xml, job-scheduler/src/main/java/org/hawkular/metrics/scheduler/impl/LockManager.java, job-scheduler/src/main/java/org/hawkular/metrics/scheduler/impl/SchedulerImpl.java, job-scheduler/src/test/java/org/hawkular/metrics/scheduler/impl/JobExecutionTest.java
This commit also increases the timeouts in JobExecutionTest.executeLotsOfJobs
because of intermittent failures on travis. On my box the test only executes
8 jobs, but on travis it runs 64 jobs. I don't think the 30 second timeout
used is always enough time.
=> [HWKMETRICS-486] use exclusive lock for job execution

core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/AvailabilityITest.java, dist/component-ear/pom.xml, dist/standalone-ear/pom.xml, integration-tests/rest-tests-jaxrs-dist/pom.xml, pom.xml
The alerting war contained an older hawkular-metrics-model
jar. This was due to a circular dep forced by having the metrics
x-alerter in the alerting repo. The x-alerter is removed from
Halerts 1.2.2.Final, (to be migrated to Hmetrics in 0.21.0), so
change dep to 1.2.2.Final for all but the alerter, leave that at
1.2.1.Final for this micro release to bridge the gap between now
and the Hmetrics 0.21.0 release.
- Also, add a compression itest for avail data
@stefannegrea please review.
=> HWKMETRICS-501 Fix

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccess.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccessImpl.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsService.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/TagQueryParser.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/transformers/TagsIndexRowTransformer.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/DelegatingDataAccess.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/BaseMetricsITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/TagsITest.java
Add the ability to filter metrics from tags without a certain tag being set, query format is !tagName:* (value is actually ignored, so it does not matter what is set)
=> [HWKMETRICS-480] Ability to filter with non-existing tagName

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/log/RestLogger.java, api/metrics-api-util/src/main/java/org/hawkular/metrics/api/jaxrs/config/ConfigurationKey.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/BaseITest.java, integration-tests/rest-tests-jaxrs/pom.xml, job-scheduler/src/test/java/org/hawkular/metrics/scheduler/impl/JobSchedulerTest.java
I have made it configurable so we can set it for REST tests as well. This will
shave quite a few seconds off of the time for schema updates to complete.
=> [HWKMETRICS-504] set schema refresh interval to zero for tests

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/AggregatedStatsQueryRequest.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/QueryRequest.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricsServiceHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/StringHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/template/IMetricsHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/param/TimeAndBucketParams.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/param/TimeAndSortParams.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsService.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/CounterITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/GaugeITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/TagsITest.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/AvailabilityITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CountersITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/GaugeMetricStatisticsITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/GaugesITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/StringITest.groovy
- Add fromEarliest in raw/rate/stats queries, for all types of metrics
- To avoid more and more duplicated code, refactored query building; now most of the parameters validation is centralized in "TimeAndSortParams" and "TimeAndBucketParams" and their builders
- Some little changes in the MetricsService java api to uniformize method calls with "BucketConfig"
=> [HWKMETRICS-445] add "fromEarliest" on most query endpoints

core/metrics-core-service/src/main/java/org/hawkular/metrics/core/jobs/CompressData.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/transformers/SortedMerge.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/operators/SortedMergeTest.java
This PR is intended to fix some behavior that's still failing in the compressionJob.
* Add retry capabilities to the compressBlock, to ensure that the execution never fails.
* TODO Requires still delayed retry
* Add mergeSort if out-of-order writes come very late
Metrics and manual running in different PR.
=> [HWKMETRICS-494] Retry on failures in compressJob

core/schema/src/main/resources/org/hawkular/schema/updates/schema-0.15.0.groovy, core/schema/src/main/resources/org/hawkular/schema/updates/schema-0.18.0.groovy, core/schema/src/main/resources/org/hawkular/schema/updates/schema-0.19.0.groovy, core/schema/src/main/resources/org/hawkular/schema/updates/schema-0.20.0.groovy, pom.xml
The verification checks are used in restart scenarios to help determine whether
or not a change, such as creating a table, has already been applied. Applying
the schema change and updating the changelog table cannot be done atomically
so we need to do some extra work to make sure we are in a known, good state.
=> [HWKMETRICS-495] upgrade to cassalog 0.4.0 and add verification checks

core/metrics-core-service/src/main/java/org/hawkular/metrics/core/jobs/JobsService.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/jobs/JobsServiceImpl.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/jobs/CompressDataJobITest.java, core/schema/src/main/java/org/hawkular/metrics/schema/SchemaService.java, core/schema/src/main/resources/org/hawkular/schema/updates/schema-0.21.0.groovy, job-scheduler/src/main/java/org/hawkular/metrics/scheduler/api/JobDetails.java, job-scheduler/src/main/java/org/hawkular/metrics/scheduler/api/JobStatus.java, job-scheduler/src/main/java/org/hawkular/metrics/scheduler/api/Scheduler.java, job-scheduler/src/main/java/org/hawkular/metrics/scheduler/impl/JobsService.java, job-scheduler/src/main/java/org/hawkular/metrics/scheduler/impl/SchedulerImpl.java, job-scheduler/src/main/java/org/hawkular/metrics/scheduler/impl/TestScheduler.java, job-scheduler/src/test/java/org/hawkular/metrics/scheduler/impl/JobExecutionTest.java, job-scheduler/src/test/java/org/hawkular/metrics/scheduler/impl/JobSchedulerTest.java
This commit includes a bunch of changes.
* Store job details in scheduled_jobs_idx
I previously only stored the job id in scheduled_jobs_idx and fetched the
details from the jobs table. This eliminates the extra read. I also am no
longer storing the job details in the jobs table. Right now it doesn't really
serve a purpose, and it has actually made things a little more complex because
there are times when the next trigger gets persisted and the job for the
current trigger still has to be retried.
* Do not updated finished_jobs_idx until other post-execution steps are done
I previously updated finished_jobs_idx right after the job was done executing.
If a subsequent post-execution step failed, namely reschulding, the job would
never run again because the computeRemainingJobs() method which …
=> [HWKMETRICS-505] Several changes to improve error handling

dist/component/component-war/pom.xml, dist/component/component-war/src/main/java/org/hawkular/metrics/component/MetricsJNDIPublisher.java
- change from @ApplicationScoped+@Eager to @Singleton+@Startup
- In general Hmetrics does not use EJB, but I have not found a
way to get this working using other annotations.  This is only
not in any metrics jars, just the component war.
@stefannegrea @jsanda @pavolloffay Please review and decide whether you are OK with using EJB annotations to solve this issue.  I know EJB is a four-letter word in Hmetrics, but I did not see another way to get this working.  I am open to alternatives if you have suggestions.
=> hwkmetrics-512 jndi bind issue

core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/transformers/DataPointCompressTransformer.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/transformers/DataPointDecompressTransformer.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/CounterITest.java
This changes the usage of gorilla-tsc by avoiding storing with compressValue(long, long). This compression version has bug in it that might in some cases return wrong values from the compressed block.
This change avoids that issue.
=> Store all values as doubles in the compression block

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/log/RestLogger.java, api/metrics-api-util/src/main/java/org/hawkular/metrics/api/jaxrs/config/ConfigurationKey.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/log/CoreLogger.java, core/schema/src/main/resources/org/hawkular/schema/updates/schema-0.21.0.groovy
If insertion of data points fail, we will use an exponential back off delay
with caps on the delay and the number of retries. The max delay and max number
of retries are stored in the sys_config table and can be updated via system
properties or environment variables.
=> [HWKMETRICS-510] add configurable retry logic for inserting data points

alerting/alerter-war/pom.xml, alerting/alerter-war/src/main/java/org/hawkular/metrics/alerter/ExpressionManager.java, alerting/alerter-war/src/main/webapp/WEB-INF/web.xml
- use ISPN CacheManager to inspect and react to cluster topology
- limit expression evaluation to only the cooridinater node
@lucasponce Please review as you are expert in cluster topology handling via CacheManager
@stefannegrea Please also optionally review
=> HWKMETRICS-515 Make external alerter cluster-aware

clients/ptranslator/pom.xml, pom.xml
Migrate ptrans ITest to run against standalone ear as opposed to the jaxrs war, which is no longer a formal dist.
=> Migrate ptrans ITest to run against standalone ear

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java, api/metrics-api-util/src/main/java/org/hawkular/metrics/api/jaxrs/config/ConfigurationKey.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/jobs/CompressData.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/jobs/JobsServiceImpl.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccess.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccessImpl.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsService.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/jobs/CompressDataJobITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/DataAccessITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/DelegatingDataAccess.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/AvailabilityITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/BaseMetricsITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/CounterITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/GaugeITest.java
The compression job defaults to a page size of 1,000. This only effects queries
on raw data.
=> [HWKMETRICS-520] make query page size configurable

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java, api/metrics-api-util/src/main/java/org/hawkular/metrics/api/jaxrs/config/ConfigurationKey.java, core/configuration-service/src/main/java/org/hawkular/metrics/sysconfig/Configuration.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/jobs/CompressData.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/jobs/JobsServiceImpl.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/jobs/CompressDataJobITest.java
The job can be enabled/disabled with either the system property
```
-Dhawkular.metrics.jobs.compression.enabled=false
```
or using the environment variable
`export COMPRESSION_JOB_ENABLED=false`
The job actually still runs but is just a no-op. This is important from a job scheduling standpoint. 
suppose the job is disabled just before 13:00, and it is re-enabled at 23:00. Raw data ingested
between 11:00 and 21:00 will not get compressed.
This has to be merged after [PR 665](https://github.com/hawkular/hawkular-metrics/pull/665).
=> [HWKMETRICS-524] add flag for disabling compression job

api/metrics-api-jaxrs/pom.xml, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/DistributedLock.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java, api/metrics-api-jaxrs/src/main/webapp/WEB-INF/web.xml, clients/ptranslator/pom.xml, dist/component/component-war/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, dist/standalone/wildfly-standalone/src/main/xsl/subsystem-templates/hawkular-alerting-infinispan.xsl, integration-tests/rest-tests-jaxrs/pom.xml
This PR requires changes to standalone.xml and standalone-ha.xml. For standalone.xml we need:
```xml
<cache-container name="hawkular-alerts" default-cache="triggers" statistics-enabled="true">
<local-cache name="partition"/>
<local-cache name="triggers"/>
<local-cache name="data"/>
<local-cache name="publish"/>
<local-cache name="schema"/>
<local-cache name="locks"/>
```
Note the addition of the **locks** cache. And for standalone-ha.xml:
```xml
<cache-container name="hawkular-alerts" 
default-cache="triggers"
module="org.wildfly.clustering.server" 
statistics-enabled="true">
<replicated-cache name="partition" mode="SYNC">
<transaction mode="BATCH"/>
</replicated-cache>
<replicated-cache name="triggers" mode="ASYNC">
<transaction mode="BATCH"/>
</replicated-cache>
<replicated-cache …
```
=> [HWKMETRICS-514] a distributed lock to coordinate schema changes

job-scheduler/src/main/java/org/hawkular/metrics/scheduler/impl/JobsService.java, job-scheduler/src/main/java/org/hawkular/metrics/scheduler/impl/ScheduledExecution.java, job-scheduler/src/main/java/org/hawkular/metrics/scheduler/impl/SchedulerImpl.java
When we go to execute a job that is already in the finished state we need to
check if the job has already been rescheduled. If so, we skip rescheduling to
avoid an execution loop.
=> [HWKMETRICS-536] check if jobs in finished state are already rescheduled

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccess.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccessImpl.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsService.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/TagQueryParser.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/DelegatingDataAccess.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/TagsITest.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/TagsITest.groovy
This PR adds the ability to fetch available tag names.
Compared to the tag values interface:
```
michael@grace-mint18 ~/projects/git/gorilla-tsc $ curl -X GET -H 'Hawkular-Tenant: t1' 'http://localhost:8080/hawkular/metrics/metrics/tags/hostname:*'
{"hostname":["localhost"]}
michael@grace-mint18 ~/projects/git/gorilla-tsc $ curl -X GET -H 'Hawkular-Tenant: t1' 'http://localhost:8080/hawkular/metrics/metrics/tags'
["hostname"]
michael@grace-mint18 ~/projects/git/gorilla-tsc $
```
=> [HWKMETRICS-532] Add /tags endpoint which fetches available tag names

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/TagsITest.groovy
The id filtering without tags allows only exact matching, so the type is required. If it's missing, return 400 instead of 500.
=> [HWKMETRICS-543] Missing type in exact id filtering should return 400

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/jobs/CompressData.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/jobs/JobsServiceImpl.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/jobs/JobsServiceImplMBean.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsService.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/CounterITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/GaugeITest.java, job-scheduler/src/main/java/org/hawkular/metrics/scheduler/impl/SchedulerImpl.java
This PR adds the ability of manually adjusting the blockSize of the compression (accepting the ISO8601 format as parameter) as well as creating MBean for the compression job triggering for given timestamp.
Calculation of the compressed range is moved from MetricsServiceImpl to CompressData to allow customized ranges to be triggered.
=> [HWKMETRICS-545] [HWKMETRICS-502] Compression job control

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/filter/AdminFilter.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AdminHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/StatusHandler.java, core/metrics-model/src/main/java/org/hawkular/metrics/model/CassandraStatus.java, core/metrics-model/src/main/java/org/hawkular/metrics/model/Status.java, integration-tests/rest-tests-jaxrs/pom.xml, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/AdminITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/RESTTest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/StatusITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/TenantITest.groovy
The output of the status endpoint now looks like:
```json
{
"MetricsService": "STARTED", 
"Built-From-Git-SHA": "291fabc1214149653ee3df14e0f2c60b10c64360", 
"Implementation-Version": "0.22.0-SNAPSHOT", 
"Cassandra": [
{
"address": "127.0.0.1", 
"status": "up"
}, 
{
"address": "127.0.0.2", 
"status": "up"
}, 
{
"address": "127.0.0.3",
"status": "up"
}
]
}
```
@mwringe does this work for you?
=> [HWKMETRICS-526] report status of Cassandra nodes

core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/BaseMetricsITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/MixedMetricsITest.java
We are seeing some errors on travis only that I am pretty sure are do to the database not being in a clean state. Since several PRs are currently blocked, I have taken the quicker route of relaxing assertions in the failing tests. 
I will create a ticket for making sure we keep the database in a consistent state between tests.
=> fix test errors on travis

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java, api/metrics-api-util/src/main/java/org/hawkular/metrics/api/jaxrs/config/ConfigurationKey.java, core/schema/src/main/java/org/hawkular/metrics/schema/SchemaService.java, core/schema/src/main/resources/org/hawkular/schema/bootstrap.groovy
It can be set at start up using the hawkular.metrics.cassandra.replication-factor
system property or the CASSANDRA_REPLICATION_FACTOR environment variable.
=> [HAWKULAR-1168] make replication_factor configurable

core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/transformers/SortedMerge.java, pom.xml
Updates RxJava version 1.2.4 (some API changes and performance improvements compared to 1.1.7)
=> Update RxJava to 1.2.4

pom.xml
(cherry picked from commit cd83a172307d7ecccd6436c6336018e09601219f)
=> [HWKMETRICS-582] Upgrade joda-time 2.7 -> 2.9.5

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/util/JobSchedulerFactory.java, job-scheduler/src/main/java/org/hawkular/metrics/scheduler/impl/LockManager.java, job-scheduler/src/main/java/org/hawkular/metrics/scheduler/impl/SchedulerImpl.java, job-scheduler/src/main/java/org/hawkular/metrics/scheduler/impl/TestScheduler.java, job-scheduler/src/test/java/org/hawkular/metrics/scheduler/impl/JobExecutionTest.java, job-scheduler/src/test/java/org/hawkular/metrics/scheduler/impl/JobSchedulingTest.java
The job lock name now includes the hostname and the queries for acquiring and
renewing locks have been modified so that a job scheduler instance can
reacquire a lock it already holds.
This commit also removes the call to reschedule a job immediately when it falls
behind schedule. I removed it because it is 1) it an optimization that is not
necessary and 2) it was causing some inconsistent behavior due to a race
condition when the indexes are read and updated.
=> [HWKMETRICS-583] some small changes to job locks

job-scheduler/src/main/java/org/hawkular/metrics/scheduler/impl/Lock.java, job-scheduler/src/main/java/org/hawkular/metrics/scheduler/impl/LockManager.java, job-scheduler/src/main/java/org/hawkular/metrics/scheduler/impl/SchedulerImpl.java
The idea is to prevent a job execution lock from expiring while the job is
running without placing too much extra load on Cassandra. job execution locks
will automatically renew once more than half the time to their expiration has
passed. If a lock is set to expire in one hour for example, then it will renew
in 30 minutes.
Single execution jobs locks have a hard coded timeout of 30 minutes. That value
is completely arbitrary. I did not want a value to small resulting in lots of
lock renewal queries.
Repepating job lock timeouts are based on the job interval. The timeout is 25%
more than the interval. The compression job runs every two hours, so the lock
timeout will be 2.5 hours and will renew in 75 minutes.
=> [HWMETRICS-570] initial support for automatic lock renewal

core/schema/src/main/java/org/hawkular/metrics/schema/SchemaService.java, core/schema/src/main/resources/org/hawkular/schema/updates/schema-0.23.0.groovy
We are also switching back to STCS for the data table because we are now doing
range deletes as part of the compression job. Eventually I think we'll switch
over to using what are essentially temporary tables for raw data that we just
drop once we are done writing to them and have compressed the data.
=> [HWKMETRICS-556] use TWCS for data_compressed table

core/schema/src/main/java/org/hawkular/metrics/schema/SchemaService.java, core/schema/src/main/resources/org/hawkular/schema/updates/schema-0.23.0.groovy
We are also switching back to STCS for the data table because we are now doing
range deletes as part of the compression job. Eventually I think we'll switch
over to using what are essentially temporary tables for raw data that we just
drop once we are done writing to them and have compressed the data.
[HWKEMTRICS-556] license header
[HWKMETRICS-556] this is what i get for trying to catch up with work on the weekend
[HWKMETRICS-556] cehckstyle
=> [HWKMETRICS-603] update compaction strategies for data tables

integration-tests/jmh-benchmark/pom.xml, integration-tests/jmh-benchmark/run.sh, integration-tests/jmh-benchmark/src/main/java/org/hawkular/metrics/benchmark/jmh/InsertBenchmark.java, integration-tests/jmh-benchmark/src/main/java/org/hawkular/metrics/benchmark/jmh/util/LiveCassandraManager.java
Refactoring of the packages in Hawkular-Metrics did not fix all the packages (such as JMH benchmarks) which are not compiled in the normal clean install process.
=> Fix JMH benchmarks to work with current version of Hawkular-Metrics.

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/filter/RequestLoggingFilter.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/StringHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/TenantsHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/util/Logged.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/util/RequestLoggingFilter.java, api/metrics-api-util/src/main/java/org/hawkular/metrics/api/jaxrs/config/ConfigurationKey.java
There are two properties that control request logging one of which is for writes. I felt it necessary to have a separate property for logging writes because it could result in lots of extra logging.
The output looks like:
```
INFO  [org.hawkular.metrics.api.jaxrs.util.RequestLoggingFilter] (default task-49)
REST API request:
--------------------------------------
path: /metrics
segments: [metrics]
method: GET
query parameters: {type=[availability]}
Tenant: T9a116f18-28cf-41b3-8ff8-c9752ac60e26232
```
=> [HWKMETRICS-589] Add REST API request logging

alerting/alerter-war/pom.xml, alerting/alerter-war/src/main/java/org/hawkular/metrics/alerter/ConditionManager.java, alerting/alerter-war/src/main/java/org/hawkular/metrics/alerter/groups/GroupTriggerManager.java, alerting/alerter-war/src/test/java/org/hawkular/metrics/alerter/groups/GroupTriggerManagerTest.java, integration-tests/rest-tests-jaxrs/pom.xml, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/alerting/AlertingITestBase.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/alerting/GroupTriggerAlerterITest.groovy
MGT support allows users to define a group trigger whose member triggers are
managed automatically by the alerter.
@lucasponce This is ready for review although it is marked DNM while I continue testing and I need to dial back some logging.
=> HWKALERTS-240 Add Metrics Group Trigger support in the metrics alerter

dist/component/component-ear/pom.xml, dist/component/component-ear/src/main/application/META-INF/jboss-deployment-structure.xml, dist/containers/hawkular-metrics-openshift-dist/pom.xml, dist/containers/hawkular-metrics-openshift-dist/src/main/application/META-INF/jboss-deployment-structure.xml, dist/standalone/standalone-ear/pom.xml, dist/standalone/standalone-ear/src/main/application/META-INF/jboss-deployment-structure.xml, pom.xml
@lucasponce This PR adds the elasticsearch stuff into the ear deployment.  It should be sanity checked using the most recent alerting master (or, actually https://github.com/hawkular/hawkular-alerts/pull/314 if it hs not yet been merged).
We'll hold the merge until we update this PR with the 1.6 release.
=> HWKMETRICS-638 Add Elasticsearch alerter to Metrics deployments

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/MetricsITest.groovy
(cherry picked from commit 8bac297c91c5bc2e7efb0432baf9748260e4380b)
=> [HWKMETRICS-621] Make /m a short alternative path to /metrics.

integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/alerting/GroupTriggerAlerterITest.groovy
(cherry picked from commit 10a6505279203c400d82f771f6e7230451e2ad9f)
#	integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/alerting/GroupTriggerAlerterITest.groovy
=> HWKMETRICS-649 GroupTriggerAlerterITest fails in slow environments

core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccess.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccessImpl.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/DelegatingDataAccess.java
This commit updates the methods for adding tags which is used by endpoints like
PUT /hawkular/metrics/gauges/{id}/tags
I did not update the method for creating metrics since it is called by
Heapster. The create metric operation also has a flag that will cause it to
use a light weight transaction. LWTs cannot be batched AFAIK so we will have
think more about how we want to handle this, in a separate ticket though. I
did also update the deleteMetric method as well to keep tags consistent there.
=> [HWKMETRICS-660] use logged batches for adding tags

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/StringHandler.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/AvailabilityITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/CountersITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/GaugesITest.groovy, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/StringITest.groovy
Adds endpoints GET /*/tags/{tags}/raw
where * is gauges|counters|strings|availability
Performs the same as POST /*/raw/query, restricted to querying by tag
=> HWKMETRICS-482 Query by tag the restful way

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java, api/metrics-api-util/src/main/java/org/hawkular/metrics/api/jaxrs/config/ConfigurationKey.java
The collection interval for internal metrics is interpreted in seconds and
defaults to 3 minutes.
I also fixed the flags for enabling internal metrics reporting so that they
are disabled by default.
=> [HWKMETRICS-689] make collection interval configurable

core/metrics-core-service/src/test/java/org/hawkular/metrics/core/jobs/CompressDataJobITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/jobs/DeleteExpiredMetricsJobITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/jobs/DeleteTenantITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/DataAccessITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/TestDataAccessFactory.java
For tests only, avoids multiple SchemaChangeListeners at the same time
=> Add missing DataAccess.shutdown() requests

pom.xml
Updates compression-gorilla to 2.0.3 and fixes the regression in Gorilla V1
=> [HWKMETRICS-700] [HWKMETRICS-701] Fixes BufferUnderflow

.travis.install.cassandra.sh, core/configuration-service/src/test/java/org/hawkular/metrics/sysconfig/ConfigurationServiceTest.java, core/schema/src/main/resources/org/hawkular/schema/bootstrap.groovy
This removes the fsync from the schema changes, so it speeds up the Cassandra's operation in the testing environment considerably.
=> Change Cassandra settings for Travis for faster tests

containers/hawkular-openshift-security-filter/src/main/java/org/hawkular/openshift/auth/OpenshiftAuthServletExtension.java, containers/hawkular-openshift-security-filter/src/main/java/org/hawkular/openshift/auth/org/hawkular/openshift/namespace/NamespaceHandler.java, containers/hawkular-openshift-security-filter/src/main/java/org/hawkular/openshift/auth/org/hawkular/openshift/namespace/NamespaceListener.java, containers/hawkular-openshift-security-filter/src/main/java/org/hawkular/openshift/auth/org/hawkular/openshift/namespace/NamespaceOverrideMapper.java
This updates the current filter to use ${OPENSHIFT_PROJECT_NAME}:${OPENSHIFT_PROJECT_ID} as the tenant name in Hawkular Metrics, instead of relying just on the project name
=> Update the tenant filter to use project id's as tenant name

api/metrics-api-jaxrs/pom.xml
Keeping using branch for SCM would inevitably cause difficulties later
=> UI scm: use tag instead of branch; update to 0.0.2

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/MetricsServiceLifecycle.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/dropwizard/RESTMetaData.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/dropwizard/RESTMetrics.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/dropwizard/RecordMetricsFilter.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AdminHandler.java, api/metrics-api-util/src/main/java/org/hawkular/metrics/api/jaxrs/config/ConfigurationKey.java, containers/hawkular-openshift-security-filter/src/main/java/org/hawkular/openshift/auth/TokenAuthenticator.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/dropwizard/DropWizardReporter.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/dropwizard/HawkularMetricRegistry.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/dropwizard/HawkularMetricsRegistryListener.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/dropwizard/HawkularObjectNameFactory.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/dropwizard/MetaData.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java
HawkularObjectNameFactory previously assumed every metric would have meta
data. TokenAuthenticator was registering metrics without meta data. I have
updated TokenAuthenticator so that it creates meta data. I have also
updated HawkularObjectNameFactory to handle the case where there is no
meta data.
There is another important change around the meta data. If a metric does
not have meta data, then its tags and data points will not get persisted.
A warning will get logged by HawkularMetricsRegistryListener about the
lack of meta data.
I have refactored the way in which internal metrics are registered.
Previously everything was done eagerly at start up. Now only meta data
is registered eagerly. Registering meta data will not cause anything to
be persisted in Cassandra. Metrics are registered …
=> [HWKMETRICS-695] Fix NPE and several other issues

core/schema/src/main/java/org/hawkular/metrics/schema/SchemaService.java, core/schema/src/main/resources/org/hawkular/schema/updates/schema-0.27.0.groovy
The change is done with the 0.27.x tag since we want this change on the 0.27.0
branch as well.
=> [HWKMETRICS-724] update data table to use TWCS - release/0.27.0 branch

containers/hawkular-openshift-security-filter/src/main/java/org/hawkular/openshift/auth/org/hawkular/openshift/namespace/NamespaceHandler.java, containers/hawkular-openshift-security-filter/src/main/java/org/hawkular/openshift/auth/org/hawkular/openshift/namespace/NamespaceListener.java
See https://issues.jboss.org/browse/HWKMETRICS-728
=> HWKMETRICS-728: fetch the namespace id directly if a miss in the namespace listener

alerting/alerter-war/src/main/java/org/hawkular/metrics/alerter/ConditionManager.java, alerting/alerter-war/src/main/java/org/hawkular/metrics/alerter/groups/GroupTriggerManager.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/CounterHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/GaugeHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/MetricsServiceHandler.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/StringHandler.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/jobs/CompressData.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccess.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccessImpl.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsService.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/tags/ExpressionTagQueryParser.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/tags/SimpleTagQueryParser.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/transformers/MetricIdentifierFromFullDataRowTransformer.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/DataAccessITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/DelegatingDataAccess.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/CounterITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/ExpressionTagQueryITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/GaugeITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/MixedMetricsITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/TagsITest.java
This PR requires PR #818 to be merged first. This removes the calls to ``metricsService.findMetric()`` in cases where it's not needed. This reduces the amount of Cassandra calls in read requests that use tags (other than fetching full metric definition).
=> [HWKMETRICS-692] Remove unnecessary calls to findMetric

api/metrics-api-util/src/main/java/org/hawkular/metrics/api/jaxrs/config/ConfigurationKey.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/DataAccessITest.java, core/rx-java-driver/src/main/java/org/hawkular/rx/cassandra/driver/RxSessionImpl.java
If there are more than 1024 inflight requests on any connected host, wait until scheduling more statements.
=> [HWKMETRICS-597] Add backpressure to the RxSession scheduling

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/filter/CacheControlFilter.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/BaseHandler.java, api/metrics-api-util/src/main/java/org/hawkular/metrics/api/jaxrs/config/ConfigurationKey.java
- Default to no-cache, but also add a config key to possibly override it
- For static HTML, use "private, max-age=86400"
- Explicitly add headers before redirect in BaseHandler on "/" when serving static html
- Add also "Vary" header for Origin and Accept-encoding
=> HWKMETRICS-736 (openshift) add explicit Cache-Control header

pom.xml
Hello @stefannegrea.
I created this PR to include this correction (htps://issues.jboss.org/browse/HWKALERTS-275) on next Hawkular Services release.
This correction prevent the ManageIQ to query for too much events. It might cause a  BusyPoolDriverException on Cassandra
From 1.6.2 to 1.6.3, there only code change was this code related to that fix. 
All the libraries still on the same version.
Best Regards,
Guilherme Baufaker Rêgo
=> [HWKMETRICS-740] Change Alerts Version to 1.6.3.Final 

pom.xml
This brings the hawkular commons version in sync with current hawkular agent
and hawkular services.
=> [HWKMETRICS-744] upgrade hawkular-commons 0.9.2->0.9.7

core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/DataAccessITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/TestDataAccessFactory.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/BaseMetricsITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/MixedMetricsITest.java
deleteMetric() used merge instead of concat which caused the tags deletion to be incomplete in certain concurrency scenarios (execution of commands is in incorrect order).
MixedMetricsITest tried to delete things twice and that way bypass test failures..
Also, add blocking for TestDataAccessFactory to make sure ``data_0`` is correctly prepared.
=> Fix MixedMetricsITest and MetricsServiceImpl.deleteMetric()

core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccess.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccessImpl.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/tags/SimpleTagQueryParser.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/DelegatingDataAccess.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/TestDataAccessFactory.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/tags/SimpleTagQueryParserTest.java
Enables the A-cost query execution (exact matches). This breaks previous behavior and as such can be disabled with a flag.
However, the advantage with large tags partitions should be huge. Needs a better regexp matching function still.
=> [HWKMETRICS-751] Improve simple tag query performance

api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/filter/AdminFilter.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/servlet/OpenshiftServlet.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/servlet/rx/ObservableServlet.java, api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/servlet/rx/ServletWriteListener.java, api/metrics-api-jaxrs/src/main/webapp/WEB-INF/web.xml, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccess.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/DataAccessImpl.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsService.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/DelegatingDataAccess.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/MetricsITest.groovy
This allows Heapster to cache all the projects with a single call to get faster startup times.
=> Add a method for fetching all the metric definitions (for Openshift)

core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/MetricsServiceImpl.java, core/metrics-core-service/src/main/java/org/hawkular/metrics/core/service/tags/SimpleTagQueryParser.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/metrics/TagsITest.java, core/metrics-core-service/src/test/java/org/hawkular/metrics/core/service/tags/SimpleTagQueryParserTest.java, integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/TenantITest.groovy
* Optimize Openshift tag queries
* [HWKMETRICS-787] clean up pod_id tag query logic and add tests
* [HWKMETRICS-787] clean up pod_id query and add some debug logging
I removed the reduce operation since it is not needed. This whole
optimization is for a particular tag key. There can only be one instance
of a tag key per request; hence, the reduce operation is not needed.
* [HWKMETRICS-787] disable failing test
I spent a few minutes investigating, but I am not going to wast any more
time. The delete tenant functionality has never been used, and the REST
integration tests are tricky due to using the "virtual clock" which in
turn makes these tests brittle.
I will open a separate ticket for disabling the delete tenant
functionality. We can leave the endpoints intact but return an
appropriate …
=> [HWKMETRICS-787] release/0.30.0 branch

dist/containers/hawkular-metrics-openshift/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
@jsanda I forgot to include this module on the OpenShift war. So now is when you try to deploy that war Wildfly throws an error about infinispan.Cache class not found.
Please review.
=> Add infinispan module to hawkular-metrics-openshift

api/metrics-api-jaxrs/pom.xml, api/metrics-api-util/pom.xml, containers/hawkular-openshift-security-filter/pom.xml, containers/pom.xml, core/configuration-service/pom.xml, core/datetime-service/pom.xml, core/metrics-core-service/pom.xml, core/metrics-model/pom.xml, core/rx-java-driver/pom.xml, core/schema-installer/pom.xml, core/schema/pom.xml, data-generator/pom.xml, dist/containers/hawkular-metrics-openshift/pom.xml, dist/pom.xml, integration-tests/jmh-benchmark/pom.xml, integration-tests/load-tests/pom.xml, integration-tests/metrics-api-jaxrs-test/pom.xml, integration-tests/pom.xml, integration-tests/rest-tests-jaxrs/pom.xml, job-scheduler/pom.xml, pom.xml
Should we start doing this, @rubenvp8510 ? It's quite a usual thing to do after releasing a version, I noticed Hawkular Metrics doesn't do that though. If it's for some reason an issue (for example for building development OpenShift images or so), we don't have to do this...
=> Move to 0.31.2.Final-SNAPSHOT
